# Experiment: Inspect MultiLepPAT GEN-RECO Matching

This notebook inspects a `MultiLepPAT` ntuple with emphasis on five questions:

1. Is the GEN-level event content kept even when reco selection is sparse?
2. How often do muons use PAT GEN refs versus the chi2 fallback?
3. How are phi-daughter kaons associated to PVs and matched back into `MC_GenPart_*`?
4. What decay signatures and mother chains are visible from the stored flat GEN collection?
5. What changes when `RequireAcceptedCandidatesForMonteCarloTree` is enabled on the DPS validation sample?

The notebook is written to prefer the recent DPS validation ntuples, and falls back to the documented validation ntuple if needed.

## Notebook Outline

- Configure the ntuple path and open `mkcands/X_data`.
- Inspect branch inventory for GEN, muon matching, and phi-kaon matching content.
- Summarize event-level GEN retention, muon match provenance, and phi-kaon match coverage.
- Inspect one event in detail, joining reco muons and fitted phi-daughter kaons to matched GEN particles.
- Rebuild decay chains from `MC_GenPart_motherGenIdx`, including the matched GEN phi for kaons.
- Compare the paired DPS validation ntuples with `RequireAcceptedCandidatesForMonteCarloTree=False/True`.

In [1]:
from pathlib import Path
from collections import Counter
from math import hypot, isfinite

import ROOT
from IPython.display import display

try:
    import pandas as pd
except ImportError:
    pd = None

ROOT.gROOT.SetBatch(True)

CANDIDATE_NTUPLES = [
    Path('/tmp/conf_dps120_switch_false_numEvent10000.root'),
    Path('/tmp/conf_dps120_switch_true_numEvent10000.root'),
    Path('/tmp/dps_phi_vertexdiag_numEvent1000.root'),
    Path('/tmp/dps_phi_kaonmatch_1000_numEvent1000.root'),
    Path('/tmp/dps_phi_kaonmatch_numEvent100.root'),
    Path('/eos/user/c/chiw/JpsiJpsiPhi/CMSSW_15_0_15_JpsiJpsiPhi_refactor/src/HeavyFlavorAnalysis/TPS-Onia2MuMu/conf_dps120_switch_true_numEvent10000.root'),
    Path('/eos/user/c/chiw/JpsiJpsiPhi/CMSSW_15_0_15_JpsiJpsiPhi_refactor/src/HeavyFlavorAnalysis/TPS-Onia2MuMu/dps_phi_kaonmatch_1000_numEvent1000.root'),
]
RETENTION_VALIDATION_NTUPLES = {
    'keep_all_mc_events': Path('/tmp/conf_dps120_switch_false_numEvent10000.root'),
    'require_candidates': Path('/tmp/conf_dps120_switch_true_numEvent10000.root'),
}
VALIDATION_NTUPLE = Path('/tmp/maxevents_fix_check_numEvent5.root')
TREE_PATH = 'mkcands/X_data'

NTUPLE_PATH = next((path for path in CANDIDATE_NTUPLES if path.exists()), VALIDATION_NTUPLE)
if not NTUPLE_PATH.exists():
    raise FileNotFoundError('Set NTUPLE_PATH to a valid MultiLepPAT ntuple before running the notebook.')

root_file = ROOT.TFile.Open(str(NTUPLE_PATH), 'READ')
tree = root_file.Get(TREE_PATH)
if not tree:
    raise RuntimeError(f'Could not find {TREE_PATH} in {NTUPLE_PATH}')

print(f'Using ntuple: {NTUPLE_PATH}')
print(f'Entries in {TREE_PATH}: {tree.GetEntries()}')

Using ntuple: /eos/user/c/chiw/JpsiJpsiPhi/CMSSW_15_0_15_JpsiJpsiPhi_refactor/src/HeavyFlavorAnalysis/TPS-Onia2MuMu/conf_dps120_switch_true_numEvent10000.root
Entries in mkcands/X_data: 119

In [2]:
for branch in tree.GetListOfBranches():
    print(branch.GetName())

TrigRes
TrigNames
MatchJpsiTriggerNames
MatchUpsTriggerNames
L1TrigRes
evtNum
runNum
lumiNum
nGoodPrimVtx
priVtxX
priVtxY
priVtxZ
priVtxXE
priVtxYE
priVtxZE
priVtxChiNorm
priVtxChi
priVtxCL
PriVtxXCorrX
PriVtxXCorrY
PriVtxXCorrZ
PriVtxXCorrEX
PriVtxXCorrEY
PriVtxXCorrEZ
PriVtxXCorrC2
PriVtxXCorrCL
nRecVtx
RecVtx_x
RecVtx_y
RecVtx_z
RecVtx_xErr
RecVtx_yErr
RecVtx_zErr
RecVtx_chi2
RecVtx_ndof
RecVtx_vtxProb
RecVtx_nTracks
nMu
muPx
muPy
muPz
muD0
muD0E
muDz
muChi2
muGlChi2
mufHits
muFirstBarrel
muFirstEndCap
muDzVtx
muDxyVtx
muNDF
muGlNDF
muPhits
muShits
muGlMuHits
muType
muQual
muTrack
muCharge
muIsoratio
munMatchedSeg
muIsGoodSoftMuonNewIlseMod
muIsGoodSoftMuonNewIlse
muIsGoodLooseMuonNew
muIsGoodLooseMuon
muIsGoodTightMuon
muIsGlobalMuon
muIsPatLooseMuon
muIsPatTightMuon
muIsPatSoftMuon
muIsPatMediumMuon
muFromPV
muPVAssocQuality
muPxErr
muPyErr
muPzErr
muPtErr
muVertexId
muDzAssocPV
muDxyAssocPV
muFromPVAssocPV
muPdgId
muPackedMatchIdx
muPackedMatchMethod
muPackedMatchVectorRelP
muPackedMatchChi2
muPackedMatchDzPV
muPackedMatchDzAssocPV
muGenMatchIdx
muGenMatchSource
muGenMatchChi2
muIsJpsiTrigMatch
muIsUpsTrigMatch
muIsJpsiFilterMatch
muIsUpsFilterMatch
muMVAMuonID
musegmentCompatibility
mupulldXdZ_pos_noArb
mupulldYdZ_pos_noArb
mupulldXdZ_pos_ArbDef
mupulldYdZ_pos_ArbDef
mupulldXdZ_pos_ArbST
mupulldYdZ_pos_ArbST
mupulldXdZ_pos_noArb_any
mupulldYdZ_pos_noArb_any
muMatch_nCandidates
muMatch_bestRelDiff
muMatch_bestDz
muMatch_methodUsed
Jpsi_1_mass
Jpsi_1_massErr
Jpsi_1_massDiff
Jpsi_1_ctau
Jpsi_1_ctauErr
Jpsi_1_Chi2
Jpsi_1_ndof
Jpsi_1_VtxProb
Jpsi_1_px
Jpsi_1_py
Jpsi_1_pz
Jpsi_1_phi
Jpsi_1_eta
Jpsi_1_pt
Jpsi_1_pxErr
Jpsi_1_pyErr
Jpsi_1_pzErr
Jpsi_1_ptErr
Jpsi_1_mu_1_Idx
Jpsi_1_mu_2_Idx
Jpsi_2_mass
Jpsi_2_massErr
Jpsi_2_massDiff
Jpsi_2_ctau
Jpsi_2_ctauErr
Jpsi_2_Chi2
Jpsi_2_ndof
Jpsi_2_VtxProb
Jpsi_2_px
Jpsi_2_py
Jpsi_2_pz
Jpsi_2_phi
Jpsi_2_eta
Jpsi_2_pt
Jpsi_2_pxErr
Jpsi_2_pyErr
Jpsi_2_pzErr
Jpsi_2_ptErr
Jpsi_2_mu_1_Idx
Jpsi_2_mu_2_Idx
Phi_mass
Phi_massErr
Phi_massDiff
Phi_ctau
Phi_ctauErr
Phi_Chi2
Phi_ndof
Phi_VtxProb
Phi_px
Phi_py
Phi_pz
Phi_phi
Phi_eta
Phi_pt
Phi_pxErr
Phi_pyErr
Phi_pzErr
Phi_ptErr
Phi_fitPass
Phi_commonAssocPVPass
Phi_commonAssocPVIdx
Phi_trackPVPass
Phi_vertexCriteriaPass
Phi_maxAbsDzPV
Phi_maxAbsDxyPV
Phi_K_1_Idx
Phi_K_2_Idx
Pri_mass
Pri_massErr
Pri_ctau
Pri_ctauErr
Pri_Chi2
Pri_ndof
Pri_VtxProb
Pri_px
Pri_py
Pri_pz
Pri_phi
Pri_eta
Pri_pt
Pri_pxErr
Pri_pyErr
Pri_pzErr
Pri_ptErr
Pri_fitValid
Pri_fitPass
Pri_assocPVPass
Pri_assocPVIdx
Pri_trackPVPass
Pri_passAny
Pri_maxAbsDzPV
Pri_maxAbsDxyPV
Phi_K_1_px
Phi_K_1_py
Phi_K_1_pz
Phi_K_1_phi
Phi_K_1_eta
Phi_K_1_pt
Phi_K_1_fromPV
Phi_K_1_pvAssocQuality
Phi_K_1_hasAssocPV
Phi_K_1_passDzPV
Phi_K_1_passDxyPV
Phi_K_1_passTrackPV
Phi_K_1_vertexId
Phi_K_1_dzPV
Phi_K_1_dxyPV
Phi_K_1_dzAssocPV
Phi_K_1_dxyAssocPV
Phi_K_1_genMatchIdx
Phi_K_1_genMatchSource
Phi_K_1_genMatchChi2
Phi_K_2_px
Phi_K_2_py
Phi_K_2_pz
Phi_K_2_phi
Phi_K_2_eta
Phi_K_2_pt
Phi_K_2_fromPV
Phi_K_2_pvAssocQuality
Phi_K_2_hasAssocPV
Phi_K_2_passDzPV
Phi_K_2_passDxyPV
Phi_K_2_passTrackPV
Phi_K_2_vertexId
Phi_K_2_dzPV
Phi_K_2_dxyPV
Phi_K_2_dzAssocPV
Phi_K_2_dxyAssocPV
Phi_K_2_genMatchIdx
Phi_K_2_genMatchSource
Phi_K_2_genMatchChi2
Ups_mass
Ups_massErr
Ups_massDiff
Ups_ctau
Ups_ctauErr
Ups_Chi2
Ups_ndof
Ups_VtxProb
Ups_px
Ups_py
Ups_pz
Ups_phi
Ups_eta
Ups_pt
Ups_pxErr
Ups_pyErr
Ups_pzErr
Ups_ptErr
Ups_mu_1_Idx
Ups_mu_2_Idx
MC_GenPart_pdgId
MC_GenPart_status
MC_GenPart_motherPdgId
MC_GenPart_motherGenIdx
MC_GenPart_handleIndex
MC_GenPart_px
MC_GenPart_py
MC_GenPart_pz
MC_GenPart_mass
MC_GenPart_pt
MC_GenPart_eta
MC_GenPart_phi

In [3]:
branches = [branch.GetName() for branch in tree.GetListOfBranches()]
focus_branches = [
    name for name in branches
    if name.startswith('MC_GenPart')
    or name in {
        'Pri_fitValid',
        'Pri_fitPass',
        'Pri_assocPVPass',
        'Pri_assocPVIdx',
        'Pri_trackPVPass',
        'Pri_passAny',
        'Pri_maxAbsDzPV',
        'Pri_maxAbsDxyPV',
        'Phi_fitPass',
        'Phi_commonAssocPVPass',
        'Phi_commonAssocPVIdx',
        'Phi_trackPVPass',
        'Phi_vertexCriteriaPass',
        'Phi_maxAbsDzPV',
        'Phi_maxAbsDxyPV',
    }
    or name.startswith('muGenMatch')
    or name.startswith('Phi_K_1_genMatch')
    or name.startswith('Phi_K_2_genMatch')
    or name in {
        'muVertexId',
        'Phi_K_1_vertexId', 'Phi_K_2_vertexId',
        'Phi_K_1_hasAssocPV', 'Phi_K_2_hasAssocPV',
        'Phi_K_1_passDzPV', 'Phi_K_2_passDzPV',
        'Phi_K_1_passDxyPV', 'Phi_K_2_passDxyPV',
        'Phi_K_1_passTrackPV', 'Phi_K_2_passTrackPV',
        'Phi_K_1_dzPV', 'Phi_K_1_dxyPV', 'Phi_K_1_dzAssocPV', 'Phi_K_1_dxyAssocPV',
        'Phi_K_2_dzPV', 'Phi_K_2_dxyPV', 'Phi_K_2_dzAssocPV', 'Phi_K_2_dxyAssocPV',
        'Phi_K_1_Idx', 'Phi_K_2_Idx',
        'Jpsi_1_mu_1_Idx', 'Jpsi_1_mu_2_Idx',
        'Jpsi_2_mu_1_Idx', 'Jpsi_2_mu_2_Idx',
        'Ups_mu_1_Idx', 'Ups_mu_2_Idx',
    }
]

for name in focus_branches:
    print(name)

muVertexId
muGenMatchIdx
muGenMatchSource
muGenMatchChi2
Jpsi_1_mu_1_Idx
Jpsi_1_mu_2_Idx
Jpsi_2_mu_1_Idx
Jpsi_2_mu_2_Idx
Phi_fitPass
Phi_commonAssocPVPass
Phi_commonAssocPVIdx
Phi_trackPVPass
Phi_vertexCriteriaPass
Phi_maxAbsDzPV
Phi_maxAbsDxyPV
Phi_K_1_Idx
Phi_K_2_Idx
Pri_fitValid
Pri_fitPass
Pri_assocPVPass
Pri_assocPVIdx
Pri_trackPVPass
Pri_passAny
Pri_maxAbsDzPV
Pri_maxAbsDxyPV
Phi_K_1_hasAssocPV
Phi_K_1_passDzPV
Phi_K_1_passDxyPV
Phi_K_1_passTrackPV
Phi_K_1_vertexId
Phi_K_1_dzPV
Phi_K_1_dxyPV
Phi_K_1_dzAssocPV
Phi_K_1_dxyAssocPV
Phi_K_1_genMatchIdx
Phi_K_1_genMatchSource
Phi_K_1_genMatchChi2
Phi_K_2_hasAssocPV
Phi_K_2_passDzPV
Phi_K_2_passDxyPV
Phi_K_2_passTrackPV
Phi_K_2_vertexId
Phi_K_2_dzPV
Phi_K_2_dxyPV
Phi_K_2_dzAssocPV
Phi_K_2_dxyAssocPV
Phi_K_2_genMatchIdx
Phi_K_2_genMatchSource
Phi_K_2_genMatchChi2
Ups_mu_1_Idx
Ups_mu_2_Idx
MC_GenPart_pdgId
MC_GenPart_status
MC_GenPart_motherPdgId
MC_GenPart_motherGenIdx
MC_GenPart_handleIndex
MC_GenPart_px
MC_GenPart_py
MC_GenPart_pz
MC_GenPart_mass
MC_GenPart_pt
MC_GenPart_eta
MC_GenPart_phi

In [21]:
PDG_LABELS = {
    443: 'J/psi',
    -443: 'J/psi',
    553: 'Upsilon',
    -553: 'Upsilon',
    333: 'phi',
    -333: 'phi',
    13: 'mu-',
    -13: 'mu+',
    321: 'K+',
    -321: 'K-',
}

MU_MATCH_SOURCE_LABELS = {0: 'unmatched', 1: 'patRef', 2: 'chi2Fallback'}
KAON_MATCH_SOURCE_LABELS = {0: 'unmatched', 1: 'phiMotherChi2', 2: 'chi2Fallback'}

def pdg_label(pdg_id):
    return PDG_LABELS.get(int(pdg_id), str(int(pdg_id)))

def as_list(vec):
    return list(vec) if vec is not None else []

def maybe_frame(rows):
    if pd is not None:
        return pd.DataFrame(rows)
    return rows

def walk_mother_chain(gen_rows, start_idx, max_depth=8):
    chain = []
    idx = int(start_idx)
    seen = set()
    while 0 <= idx < len(gen_rows) and idx not in seen and len(chain) < max_depth:
        seen.add(idx)
        row = gen_rows[idx]
        chain.append(f"{idx}:{row['particle']}")
        idx = int(row['mother_idx'])
    return ' <- '.join(chain)

def find_ancestor_idx(gen_rows, start_idx, target_abs_pdg_id):
    idx = int(start_idx)
    seen = set()
    while 0 <= idx < len(gen_rows) and idx not in seen:
        seen.add(idx)
        row = gen_rows[idx]
        if abs(int(row['pdg_id'])) == target_abs_pdg_id:
            return idx
        idx = int(row['mother_idx'])
    return -1

def first_entry_with_phi(tree):
    for entry in range(tree.GetEntries()):
        tree.GetEntry(entry)
        if hasattr(tree, 'Phi_K_1_Idx') and tree.Phi_K_1_Idx.size() > 0:
            # Further check if the kaons have GEN-level kaon matches to ensure it's a genuine phi candidate
            for idx in range(tree.Phi_K_1_Idx.size()):
                gen_match_K1_idx = int(getattr(tree, 'Phi_K_1_genMatchIdx', ROOT.std.vector('int')())[idx]) if hasattr(tree, 'Phi_K_1_genMatchIdx') else -1
                gen_match_K2_idx = int(getattr(tree, 'Phi_K_2_genMatchIdx', ROOT.std.vector('int')())[idx]) if hasattr(tree, 'Phi_K_2_genMatchIdx') else -1
                if gen_match_K1_idx != -1 and gen_match_K2_idx != -1:
                    return entry
    return 0

def entries_with_phi(tree):
    result=[]
    for entry in range(tree.GetEntries()):
        tree.GetEntry(entry)
        if hasattr(tree, 'Phi_K_1_Idx') and tree.Phi_K_1_Idx.size() > 0:
            # Further check if the kaons have GEN-level kaon matches to ensure it's a genuine phi candidate
            for idx in range(tree.Phi_K_1_Idx.size()):
                gen_match_K1_idx = int(getattr(tree, 'Phi_K_1_genMatchIdx', ROOT.std.vector('int')())[idx]) if hasattr(tree, 'Phi_K_1_genMatchIdx') else -1
                gen_match_K2_idx = int(getattr(tree, 'Phi_K_2_genMatchIdx', ROOT.std.vector('int')())[idx]) if hasattr(tree, 'Phi_K_2_genMatchIdx') else -1
                if gen_match_K1_idx != -1 and gen_match_K2_idx != -1:
                    result.append(entry)
                    break
    return result

def event_snapshot(tree, entry):
    tree.GetEntry(entry)

    gen_rows = []
    for idx, pdg_id in enumerate(as_list(tree.MC_GenPart_pdgId)):
        gen_rows.append({
            'gen_idx': idx,
            'handle_index': int(tree.MC_GenPart_handleIndex[idx]) if hasattr(tree, 'MC_GenPart_handleIndex') else -1,
            'pdg_id': int(pdg_id),
            'particle': pdg_label(pdg_id),
            'status': int(tree.MC_GenPart_status[idx]),
            'mother_idx': int(tree.MC_GenPart_motherGenIdx[idx]),
            'mother_pdg_id': int(tree.MC_GenPart_motherPdgId[idx]),
            'mother': pdg_label(tree.MC_GenPart_motherPdgId[idx]),
            'pt': float(tree.MC_GenPart_pt[idx]),
            'eta': float(tree.MC_GenPart_eta[idx]),
            'phi': float(tree.MC_GenPart_phi[idx]),
            'mass': float(tree.MC_GenPart_mass[idx]),
        })

    mu_rows = []
    mu_px = as_list(tree.muPx)
    mu_py = as_list(tree.muPy)
    mu_pz = as_list(tree.muPz)
    mu_charge = as_list(tree.muCharge)
    mu_gen_idx = as_list(tree.muGenMatchIdx) if hasattr(tree, 'muGenMatchIdx') else [-1] * len(mu_px)
    mu_gen_source = as_list(tree.muGenMatchSource) if hasattr(tree, 'muGenMatchSource') else [0] * len(mu_px)
    mu_gen_chi2 = as_list(tree.muGenMatchChi2) if hasattr(tree, 'muGenMatchChi2') else [-1.0] * len(mu_px)

    for idx, px in enumerate(mu_px):
        match_idx = int(mu_gen_idx[idx]) if idx < len(mu_gen_idx) else -1
        matched_gen = gen_rows[match_idx] if 0 <= match_idx < len(gen_rows) else None
        mu_rows.append({
            'mu_idx': idx,
            'charge': int(mu_charge[idx]),
            'pt': float(hypot(px, mu_py[idx])),
            'eta': float(0.5 * ROOT.TMath.Log((hypot(px, mu_py[idx], mu_pz[idx]) + mu_pz[idx]) / (hypot(px, mu_py[idx], mu_pz[idx]) - mu_pz[idx]))) if (hypot(px, mu_py[idx], mu_pz[idx]) - mu_pz[idx]) != 0 else float('inf') * (1 if mu_pz[idx] >= 0 else -1),
            'phi': float(ROOT.TMath.ATan2(mu_py[idx], px)),
            'vertexId': int(tree.muVertexId[idx]) if hasattr(tree, 'muVertexId') else -1,
            'match_idx': match_idx,
            'match_source': MU_MATCH_SOURCE_LABELS.get(int(mu_gen_source[idx]), int(mu_gen_source[idx])),
            'match_chi2': float(mu_gen_chi2[idx]) if idx < len(mu_gen_chi2) and isfinite(float(mu_gen_chi2[idx])) else None,
            'matched_pdg_id': matched_gen['pdg_id'] if matched_gen else None,
            'matched_particle': matched_gen['particle'] if matched_gen else None,
            'matched_mother': matched_gen['mother'] if matched_gen else None,
            'matched_mother_idx': matched_gen['mother_idx'] if matched_gen else None,
            'matched_gen_pt': matched_gen['pt'] if matched_gen else None,
        })

    phi_rows = []
    phi_specs = [
        ('K1', 'Phi_K_1_Idx', 'Phi_K_1_pt', 'Phi_K_1_eta', 'Phi_K_1_phi', 'Phi_K_1_vertexId', 'Phi_K_1_fromPV', 'Phi_K_1_pvAssocQuality',
         'Phi_K_1_hasAssocPV', 'Phi_K_1_passDzPV', 'Phi_K_1_passDxyPV', 'Phi_K_1_passTrackPV',
         'Phi_K_1_dzPV', 'Phi_K_1_dxyPV', 'Phi_K_1_dzAssocPV', 'Phi_K_1_dxyAssocPV', 'Phi_K_1_genMatchIdx', 'Phi_K_1_genMatchSource', 'Phi_K_1_genMatchChi2'),
        ('K2', 'Phi_K_2_Idx', 'Phi_K_2_pt', 'Phi_K_2_eta', 'Phi_K_2_phi', 'Phi_K_2_vertexId', 'Phi_K_2_fromPV', 'Phi_K_2_pvAssocQuality',
         'Phi_K_2_hasAssocPV', 'Phi_K_2_passDzPV', 'Phi_K_2_passDxyPV', 'Phi_K_2_passTrackPV',
         'Phi_K_2_dzPV', 'Phi_K_2_dxyPV', 'Phi_K_2_dzAssocPV', 'Phi_K_2_dxyAssocPV', 'Phi_K_2_genMatchIdx', 'Phi_K_2_genMatchSource', 'Phi_K_2_genMatchChi2'),
    ]

    phi_fit_pass = as_list(getattr(tree, 'Phi_fitPass', []))
    phi_common_assoc_pass = as_list(getattr(tree, 'Phi_commonAssocPVPass', []))
    phi_common_assoc_idx = as_list(getattr(tree, 'Phi_commonAssocPVIdx', []))
    phi_track_pv_pass = as_list(getattr(tree, 'Phi_trackPVPass', []))
    phi_vertex_pass = as_list(getattr(tree, 'Phi_vertexCriteriaPass', []))
    phi_max_abs_dz = as_list(getattr(tree, 'Phi_maxAbsDzPV', []))
    phi_max_abs_dxy = as_list(getattr(tree, 'Phi_maxAbsDxyPV', []))

    for role, idx_name, pt_name, eta_name, phi_name, vertex_name, from_pv_name, pv_quality_name, has_assoc_name, pass_dz_name, pass_dxy_name, pass_track_name, dzpv_name, dxypv_name, dzassoc_name, dxyassoc_name, gen_idx_name, gen_source_name, gen_chi2_name in phi_specs:
        idx_vec = as_list(getattr(tree, idx_name, []))
        pt_vec = as_list(getattr(tree, pt_name, []))
        eta_vec = as_list(getattr(tree, eta_name, []))
        phi_vec = as_list(getattr(tree, phi_name, []))
        vertex_vec = as_list(getattr(tree, vertex_name, []))
        from_pv_vec = as_list(getattr(tree, from_pv_name, []))
        pv_quality_vec = as_list(getattr(tree, pv_quality_name, []))
        has_assoc_vec = as_list(getattr(tree, has_assoc_name, []))
        pass_dz_vec = as_list(getattr(tree, pass_dz_name, []))
        pass_dxy_vec = as_list(getattr(tree, pass_dxy_name, []))
        pass_track_vec = as_list(getattr(tree, pass_track_name, []))
        dzpv_vec = as_list(getattr(tree, dzpv_name, []))
        dxypv_vec = as_list(getattr(tree, dxypv_name, []))
        dzassoc_vec = as_list(getattr(tree, dzassoc_name, []))
        dxyassoc_vec = as_list(getattr(tree, dxyassoc_name, []))
        gen_idx_vec = as_list(getattr(tree, gen_idx_name, []))
        gen_source_vec = as_list(getattr(tree, gen_source_name, []))
        gen_chi2_vec = as_list(getattr(tree, gen_chi2_name, []))

        for cand_idx, track_idx in enumerate(idx_vec):
            match_idx = int(gen_idx_vec[cand_idx]) if cand_idx < len(gen_idx_vec) else -1
            matched_gen = gen_rows[match_idx] if 0 <= match_idx < len(gen_rows) else None
            matched_phi_idx = find_ancestor_idx(gen_rows, match_idx, 333) if matched_gen else -1
            phi_rows.append({
                'phi_candidate': cand_idx,
                'kaon_role': role,
                'track_idx': int(track_idx),
                'phi_fit_pass': int(phi_fit_pass[cand_idx]) if cand_idx < len(phi_fit_pass) else -1,
                'phi_commonAssocPVPass': int(phi_common_assoc_pass[cand_idx]) if cand_idx < len(phi_common_assoc_pass) else -1,
                'phi_commonAssocPVIdx': int(phi_common_assoc_idx[cand_idx]) if cand_idx < len(phi_common_assoc_idx) else -1,
                'phi_trackPVPass': int(phi_track_pv_pass[cand_idx]) if cand_idx < len(phi_track_pv_pass) else -1,
                'phi_vertexCriteriaPass': int(phi_vertex_pass[cand_idx]) if cand_idx < len(phi_vertex_pass) else -1,
                'phi_maxAbsDzPV': float(phi_max_abs_dz[cand_idx]) if cand_idx < len(phi_max_abs_dz) else None,
                'phi_maxAbsDxyPV': float(phi_max_abs_dxy[cand_idx]) if cand_idx < len(phi_max_abs_dxy) else None,
                'pt': float(pt_vec[cand_idx]) if cand_idx < len(pt_vec) else None,
                'eta': float(eta_vec[cand_idx]) if cand_idx < len(eta_vec) else None,
                'phi': float(phi_vec[cand_idx]) if cand_idx < len(phi_vec) else None,
                'vertexId': int(vertex_vec[cand_idx]) if cand_idx < len(vertex_vec) else -1,
                'fromPV': int(from_pv_vec[cand_idx]) if cand_idx < len(from_pv_vec) else -1,
                'pvAssocQuality': int(pv_quality_vec[cand_idx]) if cand_idx < len(pv_quality_vec) else -1,
                'hasAssocPV': int(has_assoc_vec[cand_idx]) if cand_idx < len(has_assoc_vec) else -1,
                'passDzPV': int(pass_dz_vec[cand_idx]) if cand_idx < len(pass_dz_vec) else -1,
                'passDxyPV': int(pass_dxy_vec[cand_idx]) if cand_idx < len(pass_dxy_vec) else -1,
                'passTrackPV': int(pass_track_vec[cand_idx]) if cand_idx < len(pass_track_vec) else -1,
                'dzPV': float(dzpv_vec[cand_idx]) if cand_idx < len(dzpv_vec) else None,
                'dxyPV': float(dxypv_vec[cand_idx]) if cand_idx < len(dxypv_vec) else None,
                'dzAssocPV': float(dzassoc_vec[cand_idx]) if cand_idx < len(dzassoc_vec) else None,
                'dxyAssocPV': float(dxyassoc_vec[cand_idx]) if cand_idx < len(dxyassoc_vec) else None,
                'gen_match_idx': match_idx,
                'gen_match_source': KAON_MATCH_SOURCE_LABELS.get(int(gen_source_vec[cand_idx]), int(gen_source_vec[cand_idx])) if cand_idx < len(gen_source_vec) else 'unmatched',
                'gen_match_chi2': float(gen_chi2_vec[cand_idx]) if cand_idx < len(gen_chi2_vec) and isfinite(float(gen_chi2_vec[cand_idx])) else None,
                'matched_particle': matched_gen['particle'] if matched_gen else None,
                'matched_phi_gen_idx': matched_phi_idx,
                'matched_phi_particle': gen_rows[matched_phi_idx]['particle'] if 0 <= matched_phi_idx < len(gen_rows) else None,
                'gen_chain': walk_mother_chain(gen_rows, match_idx) if matched_gen else None,
            })

    return {
        'entry': entry,
        'run': int(tree.runNum),
        'lumi': int(tree.lumiNum),
        'event': int(tree.evtNum),
        'nMu': int(tree.nMu),
        'gen_rows': gen_rows,
        'mu_rows': mu_rows,
        'phi_rows': phi_rows,
    }

In [22]:
summary = {
    'entries': int(tree.GetEntries()),
    'events_gen_nonempty': 0,
    'events_with_muons': 0,
    'events_with_patref_match': 0,
    'events_with_chi2_fallback': 0,
    'events_with_phi_candidates': 0,
    'events_with_matched_phi_kaons': 0,
    'events_with_phi_common_assoc_pv': 0,
    'events_with_phi_track_pv_pass': 0,
    'events_with_phi_vertex_criteria_pass': 0,
    'total_muons': 0,
    'total_matched_muons': 0,
    'total_patref_matches': 0,
    'total_chi2_fallback_matches': 0,
    'total_phi_kaons': 0,
    'total_matched_phi_kaons': 0,
    'total_phi_candidates': 0,
    'total_phi_common_assoc_pv': 0,
    'total_phi_track_pv_pass': 0,
    'total_phi_vertex_criteria_pass': 0,
}

kaon_source_counter = Counter()

for entry in range(tree.GetEntries()):
    snap = event_snapshot(tree, entry)
    gen_rows = snap['gen_rows']
    mu_rows = snap['mu_rows']
    phi_rows = snap['phi_rows']
    phi_candidates = sorted({row['phi_candidate'] for row in phi_rows})
    phi_by_candidate = {
        cand_idx: [row for row in phi_rows if row['phi_candidate'] == cand_idx]
        for cand_idx in phi_candidates
    }

    if gen_rows:
        summary['events_gen_nonempty'] += 1
    if mu_rows:
        summary['events_with_muons'] += 1
    if any(row['match_source'] == 'patRef' for row in mu_rows):
        summary['events_with_patref_match'] += 1
    if any(row['match_source'] == 'chi2Fallback' for row in mu_rows):
        summary['events_with_chi2_fallback'] += 1
    if phi_rows:
        summary['events_with_phi_candidates'] += 1
    if any(row['gen_match_idx'] >= 0 for row in phi_rows):
        summary['events_with_matched_phi_kaons'] += 1
    if any(rows[0]['phi_commonAssocPVPass'] == 1 for rows in phi_by_candidate.values()):
        summary['events_with_phi_common_assoc_pv'] += 1
    if any(rows[0]['phi_trackPVPass'] == 1 for rows in phi_by_candidate.values()):
        summary['events_with_phi_track_pv_pass'] += 1
    if any(rows[0]['phi_vertexCriteriaPass'] == 1 for rows in phi_by_candidate.values()):
        summary['events_with_phi_vertex_criteria_pass'] += 1

    summary['total_muons'] += len(mu_rows)
    summary['total_matched_muons'] += sum(row['match_idx'] >= 0 for row in mu_rows)
    summary['total_patref_matches'] += sum(row['match_source'] == 'patRef' for row in mu_rows)
    summary['total_chi2_fallback_matches'] += sum(row['match_source'] == 'chi2Fallback' for row in mu_rows)
    summary['total_phi_kaons'] += len(phi_rows)
    summary['total_matched_phi_kaons'] += sum(row['gen_match_idx'] >= 0 for row in phi_rows)
    summary['total_phi_candidates'] += len(phi_candidates)
    summary['total_phi_common_assoc_pv'] += sum(rows[0]['phi_commonAssocPVPass'] == 1 for rows in phi_by_candidate.values())
    summary['total_phi_track_pv_pass'] += sum(rows[0]['phi_trackPVPass'] == 1 for rows in phi_by_candidate.values())
    summary['total_phi_vertex_criteria_pass'] += sum(rows[0]['phi_vertexCriteriaPass'] == 1 for rows in phi_by_candidate.values())
    kaon_source_counter.update(row['gen_match_source'] for row in phi_rows)

for key, value in summary.items():
    print(f'{key}: {value}')
display(maybe_frame([
    {'kaon_match_source': key, 'count': value}
    for key, value in sorted(kaon_source_counter.items())
]))

entries: 119
events_gen_nonempty: 119
events_with_muons: 119
events_with_patref_match: 119
events_with_chi2_fallback: 3
events_with_phi_candidates: 119
events_with_matched_phi_kaons: 26
events_with_phi_common_assoc_pv: 110
events_with_phi_track_pv_pass: 107
events_with_phi_vertex_criteria_pass: 103
total_muons: 734
total_matched_muons: 454
total_patref_matches: 451
total_chi2_fallback_matches: 3
total_phi_kaons: 2364
total_matched_phi_kaons: 64
total_phi_candidates: 1182
total_phi_common_assoc_pv: 502
total_phi_track_pv_pass: 550
total_phi_vertex_criteria_pass: 460

  kaon_match_source  count
0     phiMotherChi2     64
1         unmatched   2300

## Event Browser

Pick an event index and inspect the reco muons, fitted phi-daughter kaons, and the stored flat GEN collection for that event.

For kaons, `Phi_K_*_genMatchIdx` points into `MC_GenPart_*`, and `MC_GenPart_motherGenIdx` lets you walk from the matched kaon to its stored GEN phi when present.

In [23]:
ENTRY = first_entry_with_phi(tree)
snap = event_snapshot(tree, ENTRY)
print({key: snap[key] for key in ['entry', 'run', 'lumi', 'event', 'nMu']})
display(maybe_frame(snap['mu_rows']))
# display(maybe_frame(snap['phi_rows']))
# Full display of phi row. Transpose for better readability.
display(maybe_frame(snap['phi_rows']).T)
display(maybe_frame(snap['gen_rows']))

{'entry': 12, 'run': 1, 'lumi': 1, 'event': 75, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989
1,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168
2,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267
3,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384

,0,1,2,3,4,5,6,7,8,9
phi_candidate,0,1,2,3,4,0,1,2,3,4
kaon_role,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2
track_idx,832,832,833,866,948,833,913,834,867,991
phi_fit_pass,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,1,0,1,1,0,1,0,1,1,0
phi_commonAssocPVIdx,0,-1,0,1,-1,0,-1,0,1,-1
phi_trackPVPass,1,1,1,0,0,1,1,1,0,0
phi_vertexCriteriaPass,1,0,1,0,0,1,0,1,0,0
phi_maxAbsDzPV,0.038418,1.682741,0.031543,8.418475,13.4681,0.038418,1.682741,0.031543,8.418475,13.4681
phi_maxAbsDxyPV,0.019014,0.019014,0.005562,0.005603,0.013655,0.019014,0.019014,0.005562,0.005603,0.013655
pt,1.84668,1.84668,2.248047,1.295898,2.871094,2.248047,1.097656,3.167969,3.697266,1.356445
eta,2.3343,2.3343,2.234138,-2.459731,-0.498245,2.234138,2.495071,2.110904,-2.462844,-0.305979
phi,-2.935436,-2.935436,-3.001747,-0.866913,0.464764,-3.001747,-3.029185,3.124702,-0.944655,0.535751
vertexId,0,0,0,1,7,0,5,0,1,16
fromPV,2,2,3,1,1,3,1,3,1,1
pvAssocQuality,6,6,7,0,5,7,1,7,5,5
hasAssocPV,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,0,0,1,1,1,0,0
passDxyPV,1,1,1,1,1,1,1,1,1,1
passTrackPV,1,1,1,0,0,1,1,1,0,0
dzPV,0.038418,0.038418,-0.031543,8.418475,13.4681,-0.031543,-1.682741,0.008823,8.405684,8.534352
dxyPV,-0.019014,-0.019014,-0.003855,-0.005603,0.002175,-0.003855,-0.01412,-0.005562,0.003739,-0.013655
dzAssocPV,0.038418,0.038418,-0.031543,0.024629,-0.017861,-0.031543,-0.02375,0.008823,0.012666,0.016484
dxyAssocPV,-0.019014,-0.019014,-0.003855,-0.007437,0.00355,-0.003855,-0.016475,-0.005562,0.001815,-0.013115
gen_match_idx,19,19,20,-1,-1,20,-1,-1,-1,-1
gen_match_source,phiMotherChi2,phiMotherChi2,phiMotherChi2,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,10.372924,10.372924,4.812735,-1.0,-1.0,4.812735,-1.0,-1.0,-1.0,-1.0
matched_particle,K+,K+,K-,None,None,K-,None,None,None,None
matched_phi_gen_idx,14,14,14,-1,-1,14,-1,-1,-1,-1
matched_phi_particle,phi,phi,phi,None,None,phi,None,None,None,None
gen_chain,19:K+ <- 14:phi,19:K+ <- 14:phi,20:K- <- 14:phi,None,None,20:K- <- 14:phi,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,7.756618,0.736699,0.707369,3.096900
1,1,5,443,J/psi,23,-1,21,21,7.756618,-1.854981,-2.434224,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,15.056054,0.157442,0.587144,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,7.152129,-1.723323,-2.412941,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,14.899947,0.208131,0.601203,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,7.162815,-1.684299,-2.415642,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,14.545147,0.255119,0.590145,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,7.194256,-1.664367,-2.414291,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,14.350745,0.271151,0.590338,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,7.210456,-1.663232,-2.414634,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,14.625339,0.289144,0.575469,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,6.449072,-1.775066,-2.281049,3.127869
12,12,20,443,J/psi,2,10,443,J/psi,14.484553,0.298578,0.570254,3.096900
13,13,21,443,J/psi,2,11,443,J/psi,6.462913,-1.775595,-2.280805,3.127869
14,14,23,333,phi,2,-1,2212,2212,4.104245,2.283638,-2.973915,1.018265
15,15,39,13,mu-,1,12,443,J/psi,3.939168,-0.050372,0.539222,0.105658
16,16,40,-13,mu+,1,12,443,J/psi,10.547989,0.422285,0.581841,0.105658
17,17,41,13,mu-,1,13,443,J/psi,3.596267,-1.348646,-2.002443,0.105658
18,18,42,-13,mu+,1,13,443,J/psi,3.163384,-2.049014,-2.598505,0.105658
19,19,43,321,K+,1,14,333,phi,1.976605,2.335998,-2.942077,0.493680
20,20,44,-321,K-,1,14,333,phi,2.129572,2.231578,-3.003465,0.493680

In [24]:
entries_full = entries_with_phi(tree)
for entry in entries_full:
    snap = event_snapshot(tree, entry)
    print({key: snap[key] for key in ['entry', 'run', 'lumi', 'event', 'nMu']})
    display(maybe_frame(snap['mu_rows']))
    # display(maybe_frame(snap['phi_rows']))
    # Full display of phi row. Transpose for better readability.
    display(maybe_frame(snap['phi_rows']).T)
    display(maybe_frame(snap['gen_rows']))

{'entry': 12, 'run': 1, 'lumi': 1, 'event': 75, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989
1,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168
2,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267
3,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384

,0,1,2,3,4,5,6,7,8,9
phi_candidate,0,1,2,3,4,0,1,2,3,4
kaon_role,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2
track_idx,832,832,833,866,948,833,913,834,867,991
phi_fit_pass,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,1,0,1,1,0,1,0,1,1,0
phi_commonAssocPVIdx,0,-1,0,1,-1,0,-1,0,1,-1
phi_trackPVPass,1,1,1,0,0,1,1,1,0,0
phi_vertexCriteriaPass,1,0,1,0,0,1,0,1,0,0
phi_maxAbsDzPV,0.038418,1.682741,0.031543,8.418475,13.4681,0.038418,1.682741,0.031543,8.418475,13.4681
phi_maxAbsDxyPV,0.019014,0.019014,0.005562,0.005603,0.013655,0.019014,0.019014,0.005562,0.005603,0.013655
pt,1.84668,1.84668,2.248047,1.295898,2.871094,2.248047,1.097656,3.167969,3.697266,1.356445
eta,2.3343,2.3343,2.234138,-2.459731,-0.498245,2.234138,2.495071,2.110904,-2.462844,-0.305979
phi,-2.935436,-2.935436,-3.001747,-0.866913,0.464764,-3.001747,-3.029185,3.124702,-0.944655,0.535751
vertexId,0,0,0,1,7,0,5,0,1,16
fromPV,2,2,3,1,1,3,1,3,1,1
pvAssocQuality,6,6,7,0,5,7,1,7,5,5
hasAssocPV,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,0,0,1,1,1,0,0
passDxyPV,1,1,1,1,1,1,1,1,1,1
passTrackPV,1,1,1,0,0,1,1,1,0,0
dzPV,0.038418,0.038418,-0.031543,8.418475,13.4681,-0.031543,-1.682741,0.008823,8.405684,8.534352
dxyPV,-0.019014,-0.019014,-0.003855,-0.005603,0.002175,-0.003855,-0.01412,-0.005562,0.003739,-0.013655
dzAssocPV,0.038418,0.038418,-0.031543,0.024629,-0.017861,-0.031543,-0.02375,0.008823,0.012666,0.016484
dxyAssocPV,-0.019014,-0.019014,-0.003855,-0.007437,0.00355,-0.003855,-0.016475,-0.005562,0.001815,-0.013115
gen_match_idx,19,19,20,-1,-1,20,-1,-1,-1,-1
gen_match_source,phiMotherChi2,phiMotherChi2,phiMotherChi2,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,10.372924,10.372924,4.812735,-1.0,-1.0,4.812735,-1.0,-1.0,-1.0,-1.0
matched_particle,K+,K+,K-,None,None,K-,None,None,None,None
matched_phi_gen_idx,14,14,14,-1,-1,14,-1,-1,-1,-1
matched_phi_particle,phi,phi,phi,None,None,phi,None,None,None,None
gen_chain,19:K+ <- 14:phi,19:K+ <- 14:phi,20:K- <- 14:phi,None,None,20:K- <- 14:phi,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,7.756618,0.736699,0.707369,3.096900
1,1,5,443,J/psi,23,-1,21,21,7.756618,-1.854981,-2.434224,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,15.056054,0.157442,0.587144,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,7.152129,-1.723323,-2.412941,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,14.899947,0.208131,0.601203,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,7.162815,-1.684299,-2.415642,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,14.545147,0.255119,0.590145,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,7.194256,-1.664367,-2.414291,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,14.350745,0.271151,0.590338,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,7.210456,-1.663232,-2.414634,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,14.625339,0.289144,0.575469,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,6.449072,-1.775066,-2.281049,3.127869
12,12,20,443,J/psi,2,10,443,J/psi,14.484553,0.298578,0.570254,3.096900
13,13,21,443,J/psi,2,11,443,J/psi,6.462913,-1.775595,-2.280805,3.127869
14,14,23,333,phi,2,-1,2212,2212,4.104245,2.283638,-2.973915,1.018265
15,15,39,13,mu-,1,12,443,J/psi,3.939168,-0.050372,0.539222,0.105658
16,16,40,-13,mu+,1,12,443,J/psi,10.547989,0.422285,0.581841,0.105658
17,17,41,13,mu-,1,13,443,J/psi,3.596267,-1.348646,-2.002443,0.105658
18,18,42,-13,mu+,1,13,443,J/psi,3.163384,-2.049014,-2.598505,0.105658
19,19,43,321,K+,1,14,333,phi,1.976605,2.335998,-2.942077,0.493680
20,20,44,-321,K-,1,14,333,phi,2.129572,2.231578,-3.003465,0.493680

{'entry': 15, 'run': 1, 'lumi': 1, 'event': 33, 'nMu': 6}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,10.518838,0.855753,2.607853,0,21,patRef,18.137852,13.0,mu-,J/psi,18.0,10.766202
1,1,1,7.193713,0.736234,2.938449,0,22,patRef,3.515873,-13.0,mu+,J/psi,18.0,7.275738
2,2,1,5.359771,-2.015559,-0.301891,0,24,patRef,0.482388,-13.0,mu+,J/psi,19.0,5.343302
3,3,-1,3.024757,-2.377356,0.412579,0,23,patRef,3.211905,13.0,mu-,J/psi,19.0,2.925508
4,4,-1,1.062768,-2.140869,1.205922,0,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,1,1.044979,-1.721431,2.863135,18,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7
phi_candidate,0,1,2,3,0,1,2,3
kaon_role,K1,K1,K1,K1,K2,K2,K2,K2
track_idx,441,444,446,497,510,445,447,510
phi_fit_pass,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,1,1,0,0,1,1,0
phi_commonAssocPVIdx,-1,0,0,-1,-1,0,0,-1
phi_trackPVPass,0,1,1,0,0,1,1,0
phi_vertexCriteriaPass,0,1,1,0,0,1,1,0
phi_maxAbsDzPV,8.731322,0.155234,0.015225,8.731322,8.731322,0.155234,0.015225,8.731322
phi_maxAbsDxyPV,0.03146,0.07957,0.002595,0.037587,0.03146,0.07957,0.002595,0.037587
pt,1.380859,3.283203,2.142578,1.327148,1.232422,1.323242,1.5625,1.232422
eta,1.350444,0.441481,0.066103,2.08948,1.621632,0.359447,-0.00531,1.621632
phi,0.819842,-1.221909,2.283073,1.254328,1.122112,-1.322216,2.342546,1.122112
vertexId,0,0,0,3,4,0,0,4
fromPV,3,3,3,1,1,2,3,1
pvAssocQuality,7,7,7,1,5,1,7,5
hasAssocPV,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,0,1,1,0
passDxyPV,1,1,1,1,1,1,1,1
passTrackPV,1,1,1,1,0,1,1,0
dzPV,-0.004285,-0.001324,-0.000228,-0.355709,-8.731322,0.155234,0.015225,-8.731322
dxyPV,-0.00291,-0.000125,-0.000633,-0.037587,0.03146,-0.07957,0.002595,0.03146
dzAssocPV,-0.004285,-0.001324,-0.000228,0.19875,0.038789,0.155234,0.015225,0.038789
dxyAssocPV,-0.00291,-0.000125,-0.000633,-0.04168,0.034668,-0.07957,0.002595,0.034668
gen_match_idx,-1,-1,25,-1,-1,-1,26,-1
gen_match_source,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,phiMotherChi2,unmatched
gen_match_chi2,-1.0,-1.0,0.17661,-1.0,-1.0,-1.0,2.280893,-1.0
matched_particle,None,None,K+,None,None,None,K-,None
matched_phi_gen_idx,-1,-1,20,-1,-1,-1,20,-1
matched_phi_particle,None,None,phi,None,None,None,phi,None
gen_chain,None,None,25:K+ <- 20:phi,None,None,None,26:K- <- 20:phi,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,10.000039,1.430904,2.977139,3.096900
1,1,5,443,J/psi,23,-1,21,21,10.000039,-1.953481,-0.164453,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,16.409100,1.003636,2.646191,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,9.798093,-1.869321,-0.144343,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,16.734568,0.973683,2.665594,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,5.891606,-2.426375,-0.489250,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,16.648230,0.931467,2.644246,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,7.694824,-2.196539,0.006493,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,16.697456,0.913174,2.629325,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,8.856491,-2.076953,0.289669,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,16.611288,0.905666,2.639045,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,8.477961,-2.123210,0.076446,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,16.597185,0.900952,2.644108,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,8.168405,-2.164294,-0.021963,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,16.617159,0.886222,2.644680,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,7.941432,-2.208270,-0.021072,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,17.010933,0.863449,2.698629,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,7.922866,-2.205935,-0.023098,3.127869
18,18,26,443,J/psi,2,16,443,J/psi,17.807013,0.818022,2.741184,3.096900
19,19,27,443,J/psi,2,17,443,J/psi,7.792663,-2.216994,-0.052980,3.127869
20,20,44,333,phi,2,-1,2212,2212,3.697410,0.036995,2.308238,1.013615
21,21,55,13,mu-,1,18,443,J/psi,10.766202,0.856311,2.608634,0.105658
22,22,56,-13,mu+,1,18,443,J/psi,7.275738,0.736717,2.938017,0.105658
23,23,57,13,mu-,1,19,443,J/psi,2.925508,-2.378993,0.413020,0.105658
24,24,58,-13,mu+,1,19,443,J/psi,5.343302,-2.015297,-0.301536,0.105658
25,25,63,321,K+,1,20,333,phi,2.145293,0.066427,2.283046,0.493680
26,26,64,-321,K-,1,20,333,phi,1.553738,-0.003728,2.343025,0.493680

{'entry': 17, 'run': 1, 'lumi': 1, 'event': 164, 'nMu': 6}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,7.810125,-0.553555,-0.589274,0,28,patRef,4.033257,13.0,mu-,J/psi,23.0,7.769843
1,1,-1,4.951998,1.319454,2.619742,0,26,patRef,15.495389,13.0,mu-,J/psi,22.0,5.122694
2,2,1,4.124534,1.820401,3.054677,0,27,patRef,3.365206,-13.0,mu+,J/psi,22.0,4.217010
3,3,1,3.458463,-1.081463,-0.868558,0,29,patRef,0.790935,-13.0,mu+,J/psi,23.0,3.460217
4,4,1,1.211915,-1.599899,-0.342134,1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,-1,1.066250,-1.911144,3.106422,3,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

                                0                1          2                3
phi_candidate                   0                1          0                1
kaon_role                      K1               K1         K2               K2
track_idx                     499              507        500              509
phi_fit_pass                    1                1          1                1
phi_commonAssocPVPass           1                1          1                1
phi_commonAssocPVIdx            0                0          0                0
phi_trackPVPass                 1                1          1                1
phi_vertexCriteriaPass          1                1          1                1
phi_maxAbsDzPV           0.080469         0.000432   0.080469         0.000432
phi_maxAbsDxyPV          0.012773         0.009453   0.012773         0.009453
pt                       2.025391         2.298828   1.604492         1.628906
eta                      2.300791        -0.710105     2.2519         -0.79104
phi                       0.34191         -2.22604   0.344353        -2.299674
vertexId                        0                0          0                0
fromPV                          3                3          3                3
pvAssocQuality                  7                7          7                7
hasAssocPV                      1                1          1                1
passDzPV                        1                1          1                1
passDxyPV                       1                1          1                1
passTrackPV                     1                1          1                1
dzPV                     0.018418         0.000432   0.080469        -0.000325
dxyPV                    -0.00134        -0.000096  -0.012773         0.009453
dzAssocPV                0.018418         0.000432   0.080469        -0.000325
dxyAssocPV               -0.00134        -0.000096  -0.012773         0.009453
gen_match_idx                  -1               33         -1               34
gen_match_source        unmatched    phiMotherChi2  unmatched    phiMotherChi2
gen_match_chi2               -1.0         1.067586       -1.0         5.457755
matched_particle             None               K+       None               K-
matched_phi_gen_idx            -1               25         -1               25
matched_phi_particle         None              phi       None              phi
gen_chain                    None  33:K+ <- 25:phi       None  34:K- <- 25:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,4.561759,2.365013,2.764829,3.096900
1,1,5,443,J/psi,23,-1,21,21,4.561759,-1.696879,-0.376763,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,9.660784,1.641068,2.792110,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,4.435217,-1.658957,-0.378239,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,9.414911,1.614018,2.811842,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,7.632555,-1.123143,-0.651205,3.127869
6,6,16,443,J/psi,44,4,443,J/psi,9.162434,1.663479,2.850398,3.096900
7,7,17,443,J/psi,44,5,443,J/psi,7.654064,-1.102543,-0.653193,3.127869
8,8,20,443,J/psi,44,6,443,J/psi,9.059599,1.633937,2.853559,3.096900
9,9,21,443,J/psi,44,7,443,J/psi,8.948083,-0.967721,-0.640085,3.127869
10,10,24,443,J/psi,44,8,443,J/psi,8.972617,1.624013,2.857901,3.096900
11,11,25,443,J/psi,44,9,443,J/psi,10.105494,-0.848784,-0.647960,3.127869
12,12,29,443,J/psi,44,10,443,J/psi,8.871024,1.638309,2.821436,3.096900
13,13,30,443,J/psi,44,11,443,J/psi,10.104044,-0.845699,-0.644517,3.127869
14,14,33,443,J/psi,44,12,443,J/psi,8.824381,1.632954,2.826199,3.096900
15,15,34,443,J/psi,44,13,443,J/psi,10.824291,-0.778337,-0.673104,3.127869
16,16,37,443,J/psi,44,14,443,J/psi,8.801369,1.630840,2.827131,3.096900
17,17,38,443,J/psi,44,15,443,J/psi,11.127389,-0.750895,-0.672686,3.127869
18,18,41,443,J/psi,44,16,443,J/psi,8.815662,1.629816,2.819247,3.096900
19,19,42,443,J/psi,44,17,443,J/psi,11.122753,-0.749912,-0.672017,3.127869
20,20,45,443,J/psi,44,18,443,J/psi,8.756125,1.636789,2.818629,3.096900
21,21,46,443,J/psi,44,19,443,J/psi,11.129444,-0.750253,-0.671734,3.127869
22,22,49,443,J/psi,2,20,443,J/psi,9.124070,1.594984,2.816090,3.096900
23,23,50,443,J/psi,2,21,443,J/psi,11.136564,-0.742035,-0.675240,3.127869
24,24,62,333,phi,2,-1,2212,2212,1.587971,-0.945337,-1.704203,1.011245
25,25,63,333,phi,2,-1,2212,2212,3.925544,-0.745845,-2.256011,1.018461
26,26,74,13,mu-,1,22,443,J/psi,5.122694,1.317964,2.621062,0.105658
27,27,75,-13,mu+,1,22,443,J/psi,4.217010,1.820174,3.053736,0.105658
28,28,76,13,mu-,1,23,443,J/psi,7.769843,-0.554109,-0.589326,0.105658
29,29,77,-13,mu+,1,23,443,J/psi,3.460217,-1.081246,-0.869132,0.105658
30,30,80,-431,-431,2,-1,-433,-433,2.090821,-1.429818,-2.386152,1.968490
31,31,82,321,K+,1,24,333,phi,0.620838,-1.026522,-1.619685,0.493680
32,32,83,-321,K-,1,24,333,phi,0.970766,-0.887856,-1.758217,0.493680
33,33,84,321,K+,1,25,333,phi,2.286575,-0.710874,-2.226304,0.493680
34,34,85,-321,K-,1,25,333,phi,1.641384,-0.792399,-2.297400,0.493680
35,35,98,13,mu-,1,30,-431,-431,0.206865,-2.249999,1.685943,0.105658

{'entry': 18, 'run': 1, 'lumi': 1, 'event': 195, 'nMu': 5}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,15.730456,1.782720,1.592612,0,16,patRef,2.225233,-13.0,mu+,J/psi,12.0,15.698189
1,1,-1,7.615643,-1.056558,-1.793299,0,17,patRef,2.755647,13.0,mu-,J/psi,13.0,7.634923
2,2,-1,7.235332,0.175906,-1.656228,-1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
3,3,1,3.617060,-0.973816,-2.390300,0,18,patRef,0.295505,-13.0,mu+,J/psi,13.0,3.613951
4,4,-1,3.009521,1.449741,1.298897,0,15,patRef,3.056405,13.0,mu-,J/psi,12.0,3.047713

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
phi_candidate,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,789,789,790,791,795,795,852,852,872,907,790,792,879,936,796,797,928,936,971,972
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,1,1,0,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0
phi_commonAssocPVIdx,0,0,-1,-1,0,0,-1,-1,-1,-1,0,0,-1,-1,0,0,-1,-1,-1,-1
phi_trackPVPass,1,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0
phi_vertexCriteriaPass,1,1,0,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0
phi_maxAbsDzPV,0.005747,0.007549,5.660295,2.162573,0.021172,0.006401,2.134903,2.162573,0.998921,9.37069,0.005747,0.007549,5.660295,2.162573,0.021172,0.006401,2.134903,2.162573,0.998921,9.37069
phi_maxAbsDxyPV,0.010195,0.010166,0.067943,0.654091,0.013389,0.002671,0.028186,0.654091,0.02007,0.320922,0.010195,0.010166,0.067943,0.654091,0.013389,0.002671,0.028186,0.654091,0.02007,0.320922
pt,1.6875,1.6875,1.464844,1.108398,1.058594,1.058594,1.110352,1.110352,1.126953,1.139648,1.464844,2.931641,1.307617,1.12793,1.395508,2.152344,2.148438,1.12793,1.000977,1.386719
eta,1.550401,1.550401,1.444197,1.326457,0.432508,0.432508,1.815363,1.815363,-2.357006,-0.557024,1.444197,1.322611,1.362896,1.725272,0.310373,0.286752,1.652943,1.725272,-2.49031,-0.970489
phi,-0.959399,-0.959399,-0.889376,0.611143,0.773568,0.773568,0.536922,0.536922,2.901642,1.958938,-0.889376,-0.81829,-1.022695,0.785758,0.544248,0.738592,0.33526,0.785758,2.711811,2.177598
vertexId,0,0,0,0,0,0,4,4,4,7,0,0,5,10,0,0,9,10,20,21
fromPV,3,3,3,2,3,3,1,1,1,1,3,2,1,1,2,3,1,1,1,1
pvAssocQuality,7,7,7,5,7,7,5,5,1,1,7,6,5,1,5,7,5,1,0,1
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,0,0,1,0
passDxyPV,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1
passTrackPV,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,0,0,1,0
dzPV,0.002939,0.002939,0.005747,0.009282,0.000558,0.000558,0.859749,0.859749,0.998921,-6.088462,0.005747,0.007549,-5.660295,2.162573,-0.021172,-0.006401,-2.134903,2.162573,0.447735,-9.37069
dxyPV,0.010166,0.010166,0.010195,0.000427,-0.002671,-0.002671,0.028186,0.028186,-0.02007,0.320922,0.010195,0.007715,0.067943,0.654091,0.013389,0.001212,-0.002785,0.654091,0.006609,0.018416
dzAssocPV,0.002939,0.002939,0.005747,0.009282,0.000558,0.000558,0.094453,0.094453,0.231094,-0.27625,0.005747,0.007549,-0.022773,0.040703,-0.021172,-0.006401,-0.044492,0.040703,0.022578,0.311719
dxyAssocPV,0.010166,0.010166,0.010195,0.000427,-0.002671,-0.002671,0.027676,0.027676,-0.020332,0.321562,0.010195,0.007715,0.06707,0.6525,0.013389,0.001212,-0.005713,0.6525,0.013057,0.023926
gen_match_idx,20,20,19,-1,-1,-1,-1,-1,-1,-1,19,-1,-1,-1,-1,-1,-1,-1,-1,-1
gen_match_source,phiMotherChi2,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,3.51391,3.51391,3.524472,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3.524472,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
matched_particle,K-,K-,K+,None,None,None,None,None,None,None,K+,None,None,None,None,None,None,None,None,None
matched_phi_gen_idx,14,14,14,-1,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1
matched_phi_particle,phi,phi,phi,None,None,None,None,None,None,None,phi,None,None,None,None,None,None,None,None,None
gen_chain,20:K- <- 14:phi,20:K- <- 14:phi,19:K+ <- 14:phi,None,None,None,None,None,None,None,19:K+ <- 14:phi,None,None,None,None,None,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,9.130644,2.379021,0.999212,3.096900
1,1,5,443,J/psi,23,-1,21,21,9.130644,-1.370206,-2.142381,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,16.028578,1.896098,1.356703,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,8.978321,-1.275684,-2.158679,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,19.038296,1.774036,1.561429,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,8.952540,-1.222561,-2.171958,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,18.777147,1.744610,1.545148,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,10.106711,-1.118047,-1.795714,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,18.876705,1.747352,1.553712,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,9.647398,-1.166798,-1.967550,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,18.848518,1.737547,1.557338,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,10.137611,-1.125827,-2.015996,3.127869
12,12,20,443,J/psi,2,10,443,J/psi,18.636238,1.740285,1.545619,3.096900
13,13,21,443,J/psi,2,11,443,J/psi,10.816624,-1.061461,-1.982299,3.127869
14,14,26,333,phi,2,-1,2212,2212,3.132039,1.503487,-0.925483,1.015855
15,15,33,13,mu-,1,12,443,J/psi,3.047713,1.448440,1.299216,0.105658
16,16,34,-13,mu+,1,12,443,J/psi,15.698189,1.782504,1.592991,0.105658
17,17,35,13,mu-,1,13,443,J/psi,7.634923,-1.057186,-1.793421,0.105658
18,18,36,-13,mu+,1,13,443,J/psi,3.613951,-0.973510,-2.390174,0.105658
19,19,39,321,K+,1,14,333,phi,1.423369,1.444470,-0.887849,0.493680
20,20,40,-321,K-,1,14,333,phi,1.710517,1.549364,-0.956798,0.493680

{'entry': 39, 'run': 1, 'lumi': 1, 'event': 72, 'nMu': 6}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,8.739619,-2.270633,-2.809015,0,25,patRef,5.102115,13.0,mu-,J/psi,21.0,8.791836
1,1,1,6.895471,0.700353,-0.488686,0,24,patRef,24.731062,-13.0,mu+,J/psi,20.0,6.573273
2,2,-1,5.954624,0.698903,0.011194,0,23,patRef,2.244930,13.0,mu-,J/psi,20.0,5.956672
3,3,1,2.671038,-1.712973,-2.507626,0,26,patRef,5.829109,-13.0,mu+,J/psi,21.0,2.689675
4,4,-1,0.947729,-1.896171,-1.150238,3,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,-1,0.781730,2.146907,-0.100623,10,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9
phi_candidate,0,1,2,3,4,0,1,2,3,4
kaon_role,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2
track_idx,659,661,665,708,737,672,662,694,710,784
phi_fit_pass,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,1,0,1,0,0,1,0,1,0
phi_commonAssocPVIdx,-1,0,-1,2,-1,-1,0,-1,2,-1
phi_trackPVPass,0,1,0,0,0,0,1,0,0,0
phi_vertexCriteriaPass,0,1,0,0,0,0,1,0,0,0
phi_maxAbsDzPV,4.875023,0.023984,5.054571,3.428732,2.46866,4.875023,0.023984,5.054571,3.428732,2.46866
phi_maxAbsDxyPV,0.043558,0.005244,0.010864,0.727041,0.000319,0.043558,0.005244,0.010864,0.727041,0.000319
pt,1.742188,1.792969,1.167969,1.362305,1.429688,1.179688,1.304688,2.136719,2.298828,2.080078
eta,0.366955,-0.171026,2.404981,-2.372204,2.480239,0.663045,-0.287667,2.406262,-2.427137,2.40022
phi,2.942662,2.134142,0.36719,-1.125335,-2.705349,2.726247,2.238831,0.131738,-1.066142,-2.645389
vertexId,0,0,1,2,4,1,0,2,2,12
fromPV,3,3,1,1,1,1,3,1,1,1
pvAssocQuality,7,7,1,1,0,5,7,5,5,5
hasAssocPV,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,0,0,1,0,1,0,0,0
passDxyPV,1,1,1,0,1,1,1,1,1,1
passTrackPV,1,1,0,0,1,0,1,0,0,0
dzPV,0.001032,-0.005874,5.054571,2.975802,-1.015455,4.875023,0.023984,3.417391,3.428732,2.46866
dxyPV,-0.000014,0.005244,-0.010864,-0.727041,-0.000126,0.043558,-0.003408,-0.004961,0.012302,0.000319
dzAssocPV,0.001032,-0.005874,0.117734,-0.43625,0.013047,-0.055,0.023984,0.005415,0.016836,0.014062
dxyAssocPV,-0.000014,0.005244,-0.00707,-0.725625,-0.000443,0.039844,-0.003408,-0.003508,0.013779,-0.003518
gen_match_idx,-1,27,-1,-1,-1,-1,28,-1,-1,-1
gen_match_source,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched
gen_match_chi2,-1.0,5.197069,-1.0,-1.0,-1.0,-1.0,9.886293,-1.0,-1.0,-1.0
matched_particle,None,K+,None,None,None,None,K-,None,None,None
matched_phi_gen_idx,-1,22,-1,-1,-1,-1,22,-1,-1,-1
matched_phi_particle,None,phi,None,None,None,None,phi,None,None,None
gen_chain,None,27:K+ <- 22:phi,None,None,None,None,28:K- <- 22:phi,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,7.891206,1.132548,-0.010830,3.096900
1,1,5,443,J/psi,23,-1,21,21,7.891206,-2.593970,3.130762,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,12.926949,0.686076,-0.484754,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,7.793793,-2.540505,-3.131649,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,13.976388,0.671461,-0.318559,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,7.743102,-2.473608,-3.137419,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,13.731481,0.607736,-0.328273,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,11.171824,-2.153422,-3.083427,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,13.829623,0.584384,-0.347555,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,11.851824,-2.123937,-2.782807,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,13.977792,0.590750,-0.346130,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,10.342782,-2.263770,-2.685525,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,13.918976,0.584582,-0.347109,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,10.978833,-2.206241,-2.722602,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,12.473365,0.694167,-0.269325,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,10.999709,-2.207380,-2.730716,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,12.452182,0.692276,-0.270630,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,11.408638,-2.171192,-2.731656,3.127869
18,18,26,443,J/psi,44,16,443,J/psi,12.268237,0.708572,-0.265854,3.096900
19,19,27,443,J/psi,44,17,443,J/psi,11.414535,-2.170179,-2.732440,3.127869
20,20,28,443,J/psi,2,18,443,J/psi,12.143048,0.718630,-0.251259,3.096900
21,21,29,443,J/psi,2,19,443,J/psi,11.390154,-2.172213,-2.738534,3.127869
22,22,32,333,phi,2,-1,2212,2212,3.094117,-0.220559,2.178449,1.022147
23,23,41,13,mu-,1,20,443,J/psi,5.956672,0.698498,0.010737,0.105658
24,24,42,-13,mu+,1,20,443,J/psi,6.573273,0.700400,-0.488181,0.105658
25,25,43,13,mu-,1,21,443,J/psi,8.791836,-2.271017,-2.808005,0.105658
26,26,44,-13,mu+,1,21,443,J/psi,2.689675,-1.711173,-2.509643,0.105658
27,27,45,321,K+,1,22,333,phi,1.779968,-0.172880,2.135211,0.493680
28,28,46,-321,K-,1,22,333,phi,1.318061,-0.283522,2.236853,0.493680

{'entry': 43, 'run': 1, 'lumi': 1, 'event': 4, 'nMu': 6}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,8.788517,-1.432755,-2.225490,0,10,patRef,6.244523,-13.0,mu+,J/psi,6.0,8.541657
1,1,1,4.842495,1.940219,0.907334,0,12,patRef,9.426877,-13.0,mu+,J/psi,7.0,4.911893
2,2,1,4.800384,0.049402,0.588270,-1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
3,3,-1,3.132381,-1.960199,-2.512072,0,9,patRef,1.985404,13.0,mu-,J/psi,6.0,3.055902
4,4,-1,2.794132,2.133162,0.064034,0,11,patRef,0.833963,13.0,mu-,J/psi,7.0,2.821169
5,5,1,0.877097,-1.959345,-1.050868,1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

                                0               1          2               3
phi_candidate                   0               1          0               1
kaon_role                      K1              K1         K2              K2
track_idx                     766             773        780             774
phi_fit_pass                    1               1          1               1
phi_commonAssocPVPass           0               1          0               1
phi_commonAssocPVIdx           -1               0         -1               0
phi_trackPVPass                 0               1          0               1
phi_vertexCriteriaPass          0               1          0               1
phi_maxAbsDzPV           5.282023        0.023359   5.282023        0.023359
phi_maxAbsDxyPV          1.322342        0.015518   1.322342        0.015518
pt                       1.863281        1.503906   1.109375        1.787109
eta                     -0.728416       -1.536668  -0.728416       -1.659902
phi                      1.890981        1.342808   1.916163          1.3849
vertexId                       12               0          1               0
fromPV                          1               3          1               3
pvAssocQuality                  1               7          5               7
hasAssocPV                      1               1          1               1
passDzPV                        0               1          0               1
passDxyPV                       0               1          1               1
passTrackPV                     0               1          0               1
dzPV                    -5.282023        0.014697  -2.190767        0.023359
dxyPV                   -1.322342       -0.005781   0.078718       -0.015518
dzAssocPV                0.054141        0.014697   -0.02666        0.023359
dxyAssocPV               -1.31875       -0.005781   0.077695       -0.015518
gen_match_idx                  -1              13         -1              14
gen_match_source        unmatched   phiMotherChi2  unmatched   phiMotherChi2
gen_match_chi2               -1.0        2.856497       -1.0        7.829836
matched_particle             None              K+       None              K-
matched_phi_gen_idx            -1               8         -1               8
matched_phi_particle         None             phi       None             phi
gen_chain                    None  13:K+ <- 8:phi       None  14:K- <- 8:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,6.732587,-2.126631,-2.841964,3.096900
1,1,5,443,J/psi,23,-1,21,21,6.732587,2.187513,0.299629,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,11.094634,-1.652121,-2.347628,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,6.684059,2.157872,0.286891,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,11.068886,-1.648124,-2.356288,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,6.557600,2.178959,0.669603,3.127869
6,6,14,443,J/psi,2,4,443,J/psi,11.505303,-1.606230,-2.300838,3.096900
7,7,15,443,J/psi,2,5,443,J/psi,7.111697,2.096445,0.605481,3.127869
8,8,23,333,phi,2,-1,2212,2212,3.250006,-1.602917,1.362890,1.018449
9,9,33,13,mu-,1,6,443,J/psi,3.055902,-1.959959,-2.512381,0.105658
10,10,34,-13,mu+,1,6,443,J/psi,8.541657,-1.433212,-2.225648,0.105658
11,11,35,13,mu-,1,7,443,J/psi,2.821169,2.133253,0.065074,0.105658
12,12,36,-13,mu+,1,7,443,J/psi,4.911893,1.941076,0.905456,0.105658
13,13,40,321,K+,1,8,333,phi,1.496324,-1.534291,1.341286,0.493680
14,14,41,-321,K-,1,8,333,phi,1.754329,-1.657883,1.381316,0.493680

{'entry': 44, 'run': 1, 'lumi': 1, 'event': 166, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,8.814482,1.359120,-2.022076,0,12,patRef,0.789962,-13,mu+,J/psi,8,8.822961
1,1,-1,7.637171,1.134596,-1.723472,0,11,patRef,3.476069,13,mu-,J/psi,8,7.746225
2,2,-1,5.004640,1.252612,1.765314,0,13,patRef,0.332798,13,mu-,J/psi,9,5.006896
3,3,1,3.683686,1.895178,1.475235,0,14,patRef,4.720977,-13,mu+,J/psi,9,3.803929

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
phi_candidate,0,1,2,3,4,5,6,0,1,2,3,4,5,6
kaon_role,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2
track_idx,973,982,982,984,1131,1145,1147,1036,989,1205,985,1132,1147,1149
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,0,1,1,1,1,0,0,0,1,1,1,1
phi_commonAssocPVIdx,-1,-1,-1,0,7,7,7,-1,-1,-1,0,7,7,7
phi_trackPVPass,0,0,1,1,1,1,1,0,0,1,1,1,1,1
phi_vertexCriteriaPass,0,0,0,1,1,1,1,0,0,0,1,1,1,1
phi_maxAbsDzPV,6.528113,2.771008,1.993843,0.023867,0.717538,0.796957,0.796957,6.528113,2.771008,1.993843,0.023867,0.717538,0.796957,0.796957
phi_maxAbsDxyPV,1.35265,0.741121,0.080537,0.00251,0.031765,0.024798,0.024798,1.35265,0.741121,0.080537,0.00251,0.031765,0.024798,0.024798
pt,1.12207,2.755859,2.755859,1.324219,1.026367,2.486328,2.257812,1.161133,1.013672,1.453125,1.77832,1.40918,2.257812,1.913086
eta,-0.867214,2.015503,2.015503,1.899411,2.445631,-2.008179,-2.222053,-0.597491,2.086734,2.096805,1.716483,2.072451,-2.222053,-2.26545
phi,-0.635087,1.091924,1.091924,-0.020613,-0.825699,3.118263,3.128518,-0.541041,0.850231,1.219185,-0.066023,-1.04065,3.128518,3.127923
vertexId,0,0,0,0,7,7,7,2,1,22,0,7,7,7
fromPV,2,2,2,3,1,1,1,1,1,1,3,1,1,1
pvAssocQuality,1,6,6,7,1,0,1,1,5,1,7,5,1,0
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,1,1,1,0,0,1,1,1,1,1
passDxyPV,0,1,1,1,1,1,1,0,0,1,1,1,1,1
passTrackPV,0,1,1,1,1,1,1,0,0,1,1,1,1,1
dzPV,-0.018037,-0.013291,-0.013291,0.023867,0.711176,0.737749,0.796957,-6.528113,2.771008,1.993843,-0.017158,0.717538,0.796957,0.750571
dxyPV,0.205469,0.012334,0.012334,-0.00251,-0.019249,0.001015,0.024798,1.35265,-0.741121,-0.080537,-0.000997,-0.031765,0.024798,-0.005136
dzAssocPV,-0.018037,-0.013291,-0.013291,0.023867,0.070703,0.081406,0.14375,0.946875,0.001547,0.090313,-0.017158,0.067188,0.14375,0.098125
dxyAssocPV,0.205469,0.012334,0.012334,-0.00251,-0.019404,-0.002554,0.021191,1.35375,-0.739375,-0.083281,-0.000997,-0.033008,0.021191,-0.00874
gen_match_idx,-1,-1,-1,15,-1,-1,-1,-1,-1,-1,16,-1,-1,-1
gen_match_source,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,-1.0,0.07273,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2.499257,-1.0,-1.0,-1.0
matched_particle,None,None,None,K+,None,None,None,None,None,None,K-,None,None,None
matched_phi_gen_idx,-1,-1,-1,10,-1,-1,-1,-1,-1,-1,10,-1,-1,-1
matched_phi_particle,None,None,None,phi,None,None,None,None,None,None,phi,None,None,None
gen_chain,None,None,None,15:K+ <- 10:phi,None,None,None,None,None,None,16:K- <- 10:phi,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,11.648334,1.119149,-1.776854,3.096900
1,1,5,443,J/psi,23,-1,21,21,11.648334,1.526818,1.364739,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,12.947213,1.055132,-1.894845,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,10.098894,1.710855,1.592792,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,16.213846,1.259066,-1.905371,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,8.845991,1.598070,1.653188,3.127869
6,6,17,443,J/psi,44,4,443,J/psi,16.088980,1.251691,-1.891656,3.096900
7,7,18,443,J/psi,44,5,443,J/psi,8.857656,1.599005,1.641165,3.127869
8,8,21,443,J/psi,2,6,443,J/psi,16.384604,1.268937,-1.882495,3.096900
9,9,22,443,J/psi,2,7,443,J/psi,8.719260,1.586254,1.639896,3.127869
10,10,28,333,phi,2,-1,2212,2212,3.098236,1.797156,-0.046265,1.031673
11,11,34,13,mu-,1,8,443,J/psi,7.746225,1.134494,-1.722969,0.105658
12,12,35,-13,mu+,1,8,443,J/psi,8.822961,1.359097,-2.022416,0.105658
13,13,36,13,mu-,1,9,443,J/psi,5.006896,1.252356,1.765535,0.105658
14,14,37,-13,mu+,1,9,443,J/psi,3.803929,1.894711,1.474201,0.105658
15,15,40,321,K+,1,10,333,phi,1.321088,1.899281,-0.019995,0.493680
16,16,41,-321,K-,1,10,333,phi,1.777943,1.713858,-0.065784,0.493680
17,17,42,321,K+,1,-1,-421,-421,0.550867,4.362574,-2.050971,0.493680
18,18,47,-321,K-,1,-1,421,421,0.214715,5.354278,1.676475,0.493680

{'entry': 52, 'run': 1, 'lumi': 1, 'event': 10, 'nMu': 7}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,9.457121,1.514301,1.016459,0,14,patRef,3.930681,-13.0,mu+,J/psi,9.0,9.598712
1,1,1,6.954375,1.435378,-2.024055,0,12,patRef,3.155338,-13.0,mu+,J/psi,8.0,6.970423
2,2,-1,6.902300,1.352616,0.664969,0,13,patRef,0.871713,13.0,mu-,J/psi,9.0,6.854896
3,3,1,5.229764,0.479504,2.935811,-1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
4,4,-1,2.930440,1.842210,-2.580039,18,11,patRef,19.595213,13.0,mu-,J/psi,8.0,2.958685
5,5,-1,1.826291,1.455422,3.107290,1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,1,1.558098,1.770269,-1.413947,8,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
phi_candidate,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,1017,1020,1020,1020,1023,1024,1108,1168,1234,1279,1168,1073,1278,1289,1024,1312,1109,1314,1299,1292
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
phi_commonAssocPVIdx,-1,-1,-1,-1,0,-1,3,-1,-1,-1,-1,-1,-1,-1,0,-1,3,-1,-1,-1
phi_trackPVPass,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
phi_vertexCriteriaPass,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
phi_maxAbsDzPV,4.023828,1.317133,4.97382,0.957696,0.009868,1.663763,0.731678,4.333268,7.178953,5.195258,4.023828,1.317133,4.97382,0.957696,0.009868,1.663763,0.731678,4.333268,7.178953,5.195258
phi_maxAbsDxyPV,0.327006,0.298524,0.298524,0.298524,0.016201,0.536177,0.00063,0.141297,0.415939,0.129126,0.327006,0.298524,0.298524,0.298524,0.016201,0.536177,0.00063,0.141297,0.415939,0.129126
pt,1.021484,1.838867,1.838867,1.838867,1.705078,2.316406,1.15625,1.365234,1.476562,1.094727,1.365234,1.861328,1.091797,1.191406,2.316406,1.820312,1.294922,1.037109,1.345703,1.15918
eta,-0.049989,-1.785516,-1.785516,-1.785516,1.455733,1.342204,-2.121342,0.299753,-0.145573,2.052675,0.299753,-1.845943,-2.19953,-1.80108,1.342204,1.471847,-2.265084,0.17597,-0.501541,2.484451
phi,-3.018051,1.180315,1.180315,1.180315,-1.176897,-1.154629,-1.059513,-3.038967,2.123216,0.714972,-3.038967,0.891634,1.328174,1.295539,-1.154629,-1.201399,-1.254035,-3.018344,2.189806,0.614073
vertexId,9,23,23,23,0,0,3,6,9,14,6,2,13,15,0,25,3,26,17,16
fromPV,1,1,1,1,2,3,1,1,1,1,1,1,1,1,3,1,1,1,1,1
pvAssocQuality,1,1,1,1,6,7,0,5,5,5,5,5,5,1,7,1,0,1,1,0
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,1,1,1,0,1,0,0,1,0,1,1,1,1,0,0,0
passDxyPV,0,0,0,0,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,1
passTrackPV,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0
dzPV,1.40372,-0.957696,-0.957696,-0.957696,0.009868,-0.004878,0.703082,-4.023828,1.444636,-5.195258,-4.023828,-1.317133,-4.97382,-0.444725,-0.004878,-1.663763,0.731678,-4.333268,-7.178953,-4.796615
dxyPV,-0.327006,0.298524,0.298524,0.298524,-0.011689,0.016201,-0.000078,-0.070426,0.00796,0.129126,-0.070426,-0.140169,0.029514,0.29084,0.016201,0.536177,0.00063,0.141297,-0.415939,-0.007899
dzAssocPV,-0.049844,-0.020371,-0.020371,-0.020371,0.009868,-0.004878,0.122422,-0.001309,-0.008872,-0.068984,-0.001309,0.039395,-0.048242,0.2,-0.004878,-0.140234,0.150937,-0.065234,-0.168906,0.05043
dxyAssocPV,-0.3275,0.298906,0.298906,0.298906,-0.011689,0.016201,-0.001594,-0.070586,0.006982,0.131172,-0.070586,-0.141719,0.027891,0.291719,0.016201,0.547813,-0.001365,0.141563,-0.413437,-0.003704
gen_match_idx,-1,-1,-1,-1,15,16,-1,-1,-1,-1,-1,-1,-1,-1,16,-1,-1,-1,-1,-1
gen_match_source,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,-1.0,-1.0,2.614633,5.169485,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5.169485,-1.0,-1.0,-1.0,-1.0,-1.0
matched_particle,None,None,None,None,K+,K-,None,None,None,None,None,None,None,None,K-,None,None,None,None,None
matched_phi_gen_idx,-1,-1,-1,-1,10,10,-1,-1,-1,-1,-1,-1,-1,-1,10,-1,-1,-1,-1,-1
matched_phi_particle,None,None,None,None,phi,phi,None,None,None,None,None,None,None,None,phi,None,None,None,None,None
gen_chain,None,None,None,None,15:K+ <- 10:phi,16:K- <- 10:phi,None,None,None,None,None,None,None,None,16:K- <- 10:phi,None,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,12.494305,1.437484,-2.214614,3.096900
1,1,5,443,J/psi,23,-1,21,21,12.494305,1.553541,0.926979,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,10.419618,1.662323,-2.292355,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,14.885981,1.421691,0.988032,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,9.936684,1.605846,-2.363131,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,15.970363,1.470564,1.056436,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,9.999375,1.602448,-2.371707,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,15.919967,1.476603,1.065199,3.127869
8,8,16,443,J/psi,2,6,443,J/psi,9.613586,1.601902,-2.186791,3.096900
9,9,17,443,J/psi,2,7,443,J/psi,16.208187,1.462882,0.870250,3.127869
10,10,19,333,phi,2,-1,2212,2212,4.092263,1.392178,-1.163413,1.019086
11,11,28,13,mu-,1,8,443,J/psi,2.958685,1.838055,-2.578054,0.105658
12,12,29,-13,mu+,1,8,443,J/psi,6.970423,1.436091,-2.024204,0.105658
13,13,30,13,mu-,1,9,443,J/psi,6.854896,1.352366,0.665287,0.105658
14,14,31,-13,mu+,1,9,443,J/psi,9.598712,1.513890,1.016118,0.105658
15,15,32,321,K+,1,10,333,phi,1.762042,1.455321,-1.178714,0.493680
16,16,33,-321,K-,1,10,333,phi,2.330583,1.341839,-1.151846,0.493680

{'entry': 57, 'run': 1, 'lumi': 1, 'event': 122, 'nMu': 13}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,8.124257,1.888764,-1.652184,11,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
1,1,1,5.315836,-2.348290,0.237687,8,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
2,2,-1,5.086410,-1.868044,0.604375,0,23,patRef,4.830028,13.0,mu-,J/psi,20.0,4.926874
3,3,1,4.176823,1.848744,1.889548,0,26,patRef,8.622400,-13.0,mu+,J/psi,21.0,4.149100
4,4,-1,3.144973,2.038682,2.757776,0,25,patRef,0.705751,13.0,mu-,J/psi,21.0,3.171404
5,5,-1,1.696559,-1.678903,1.421028,36,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,1,1.448762,1.535388,-2.980745,9,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
7,7,1,1.411275,2.320868,0.131530,37,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
8,8,-1,1.369086,-1.893471,-0.853875,12,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
9,9,1,1.261891,-1.578778,-1.215972,1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
10,10,-1,1.068392,-1.886245,2.997594,34,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
11,11,1,0.965518,-2.187446,-2.054039,15,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
12,12,1,0.767396,-2.031081,-1.233694,39,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
phi_candidate,0,1,2,3,4,5,6,0,1,2,3,4,5,6
kaon_role,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2
track_idx,1412,1412,1415,1415,1427,1433,1474,1430,1714,1544,1734,1430,1662,1736
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,0,0,1,0,0,0,0,0,0,1,0,0
phi_commonAssocPVIdx,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,0,-1,-1
phi_trackPVPass,1,0,0,0,1,0,0,1,0,0,0,1,0,0
phi_vertexCriteriaPass,0,0,0,0,1,0,0,0,0,0,0,1,0,0
phi_maxAbsDzPV,0.837575,1.410189,9.523172,39.501987,0.039512,13.841685,17.061602,0.837575,1.410189,9.523172,39.501987,0.039512,13.841685,17.061602
phi_maxAbsDxyPV,0.069098,0.294808,4.729033,9.629465,0.006533,0.278469,2.045524,0.069098,0.294808,4.729033,9.629465,0.006533,0.278469,2.045524
pt,1.22168,1.22168,1.214844,1.214844,1.620117,1.225586,1.310547,1.378906,1.111328,1.053711,1.054688,1.378906,1.018555,1.106445
eta,1.530625,1.530625,-0.979461,-0.979461,1.681143,-1.549852,-1.728202,1.578967,1.700735,-1.337993,-1.35612,1.578967,-1.736259,-1.772881
phi,1.417727,1.417727,1.355909,1.355909,0.881771,2.590029,0.942502,0.993383,1.79487,1.651622,1.402493,0.993383,2.249492,1.295246
vertexId,7,7,30,30,0,0,2,0,32,6,45,0,18,45
fromPV,1,1,1,1,3,3,1,3,1,1,1,3,1,1
pvAssocQuality,1,1,1,1,7,7,5,7,1,5,1,7,1,1
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,0,0,1,1,0,1,1,0,0,1,0,0
passDxyPV,1,1,0,0,1,1,1,1,0,0,0,1,0,0
passTrackPV,1,1,0,0,1,1,0,1,0,0,0,1,0,0
dzPV,-0.837575,-0.837575,-9.523172,-9.523172,-0.008242,-0.035078,-7.474069,0.039512,-1.410189,-4.76808,-39.501987,0.039512,-13.841685,-17.061602
dxyPV,0.069098,0.069098,-4.729033,-4.729033,0.003853,-0.009282,0.010657,-0.006533,-0.294808,-0.152686,-9.629465,-0.006533,0.278469,2.045524
dzAssocPV,0.04082,0.04082,0.166406,0.166406,-0.008242,-0.035078,-0.010869,0.039512,0.018447,-0.000778,-22.620001,0.039512,0.101562,-0.179375
dxyAssocPV,0.070234,0.070234,-4.7225,-4.7225,0.003853,-0.009282,0.011406,-0.006533,-0.29125,-0.150859,-9.63,-0.006533,0.282344,2.045
gen_match_idx,-1,-1,-1,-1,28,-1,-1,27,-1,-1,-1,27,-1,-1
gen_match_source,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,-1.0,-1.0,0.400621,-1.0,-1.0,1.400164,-1.0,-1.0,-1.0,1.400164,-1.0,-1.0
matched_particle,None,None,None,None,K-,None,None,K+,None,None,None,K+,None,None
matched_phi_gen_idx,-1,-1,-1,-1,22,-1,-1,22,-1,-1,-1,22,-1,-1
matched_phi_particle,None,None,None,None,phi,None,None,phi,None,None,None,phi,None,None
gen_chain,None,None,None,None,28:K- <- 22:phi,None,None,27:K+ <- 22:phi,None,None,None,27:K+ <- 22:phi,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,6.369729,-2.593743,0.204051,3.096900
1,1,5,443,J/psi,23,-1,21,21,6.369729,2.078326,-2.937542,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,6.405616,-2.586876,0.214618,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,6.736533,2.032762,2.283692,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,9.349895,-2.217767,0.337160,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,6.732008,2.023206,2.277973,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,10.567056,-2.104444,0.368416,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,6.730391,2.013956,2.275645,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,10.569114,-2.104508,0.368373,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,6.690555,2.019992,2.265937,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,9.017877,-2.263260,0.367168,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,6.696633,2.020556,2.268667,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,9.954905,-2.164411,0.410319,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,6.697947,2.020680,2.266782,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,9.963441,-2.163567,0.411538,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,6.698061,2.020679,2.266761,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,9.963659,-2.163584,0.411538,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,6.695849,2.021009,2.265478,3.127869
18,18,26,443,J/psi,44,16,443,J/psi,9.963690,-2.163542,0.411555,3.096900
19,19,27,443,J/psi,44,17,443,J/psi,6.702077,2.020125,2.265020,3.127869
20,20,28,443,J/psi,2,18,443,J/psi,9.984307,-2.161589,0.415564,3.096900
21,21,29,443,J/psi,2,19,443,J/psi,6.657170,2.026951,2.262996,3.127869
22,22,33,333,phi,2,-1,2212,2212,3.011818,1.637244,0.933222,1.019589
23,23,46,13,mu-,1,20,443,J/psi,4.926874,-1.868115,0.603483,0.105658
24,24,47,-13,mu+,1,20,443,J/psi,5.225864,-2.352160,0.238514,0.105658
25,25,48,13,mu-,1,21,443,J/psi,3.171404,2.037932,2.757803,0.105658
26,26,49,-13,mu+,1,21,443,J/psi,4.149100,1.849830,1.891548,0.105658
27,27,53,321,K+,1,22,333,phi,1.391454,1.580574,0.992103,0.493680
28,28,54,-321,K-,1,22,333,phi,1.624840,1.681067,0.882807,0.493680

{'entry': 62, 'run': 1, 'lumi': 1, 'event': 72, 'nMu': 7}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,8.334415,1.206584,-1.281913,0,16,patRef,19.676960,-13.0,mu+,J/psi,11.0,8.510256
1,1,-1,6.779547,-1.444650,2.175660,0,13,patRef,1.121813,13.0,mu-,J/psi,10.0,6.768067
2,2,-1,5.643537,1.305742,-0.839620,0,15,patRef,2.499980,13.0,mu-,J/psi,11.0,5.665493
3,3,1,5.294716,-1.666395,2.647646,0,14,patRef,1.082683,-13.0,mu+,J/psi,10.0,5.260266
4,4,1,5.079278,0.583811,-2.562885,-1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,-1,1.474730,-1.428252,0.473237,4,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,1,0.853883,-1.950133,-0.047188,12,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

                                      0                1
phi_candidate                         0                0
kaon_role                            K1               K2
track_idx                           636              637
phi_fit_pass                          1                1
phi_commonAssocPVPass                 1                1
phi_commonAssocPVIdx                  0                0
phi_trackPVPass                       1                1
phi_vertexCriteriaPass                1                1
phi_maxAbsDzPV                 0.029199         0.029199
phi_maxAbsDxyPV                0.003638         0.003638
pt                             1.581055         2.585938
eta                            2.289804         2.274422
phi                            2.287564         2.323993
vertexId                              0                0
fromPV                                3                3
pvAssocQuality                        7                7
hasAssocPV                            1                1
passDzPV                              1                1
passDxyPV                             1                1
passTrackPV                           1                1
dzPV                          -0.029199         0.002874
dxyPV                         -0.001909        -0.003638
dzAssocPV                     -0.029199         0.002874
dxyAssocPV                    -0.001909        -0.003638
gen_match_idx                        18               17
gen_match_source          phiMotherChi2    phiMotherChi2
gen_match_chi2                 0.326912         3.342918
matched_particle                     K-               K+
matched_phi_gen_idx                  12               12
matched_phi_particle                phi              phi
gen_chain               18:K- <- 12:phi  17:K+ <- 12:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,7.778844,-2.043166,2.581985,3.096900
1,1,5,443,J/psi,23,-1,21,21,7.778844,1.847241,-0.559607,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,7.772448,-2.004299,2.603591,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,10.817645,1.555884,-1.280291,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,7.716769,-1.977203,2.604093,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,12.759138,1.412705,-1.164119,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,10.826331,-1.667697,2.522695,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,12.582806,1.371150,-1.169202,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,10.752616,-1.655778,2.523486,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,14.119793,1.262024,-1.119128,3.127869
10,10,18,443,J/psi,2,8,443,J/psi,11.700137,-1.572410,2.382017,3.096900
11,11,19,443,J/psi,2,9,443,J/psi,13.845574,1.266313,-1.106156,3.127869
12,12,21,333,phi,2,-1,2212,2212,4.257200,2.280334,2.309860,1.022281
13,13,35,13,mu-,1,10,443,J/psi,6.768067,-1.444521,2.176123,0.105658
14,14,36,-13,mu+,1,10,443,J/psi,5.260266,-1.666315,2.648192,0.105658
15,15,37,13,mu-,1,11,443,J/psi,5.665493,1.305486,-0.840323,0.105658
16,16,38,-13,mu+,1,11,443,J/psi,8.510256,1.205148,-1.281955,0.105658
17,17,39,321,K+,1,12,333,phi,2.670565,2.275203,2.323320,0.493680
18,18,40,-321,K-,1,12,333,phi,1.587284,2.288511,2.287214,0.493680

{'entry': 68, 'run': 1, 'lumi': 1, 'event': 187, 'nMu': 8}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,8.526612,-0.953015,-3.106076,0,13,patRef,3.206912,13.0,mu-,J/psi,10.0,8.449192
1,1,-1,5.398422,1.467534,-0.562725,0,15,patRef,0.015133,13.0,mu-,J/psi,11.0,5.407872
2,2,1,4.981533,-1.072238,2.710779,0,14,patRef,11.475427,-13.0,mu+,J/psi,10.0,4.936141
3,3,1,4.577511,1.778525,-0.015932,0,16,patRef,2.570218,-13.0,mu+,J/psi,11.0,4.613581
4,4,-1,1.927171,-2.114008,2.776937,6,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,-1,1.851219,-2.121807,2.764492,8,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,-1,1.153757,-2.185999,-1.075113,3,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
7,7,1,1.118851,-1.948287,-1.556170,7,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

                                      0                1
phi_candidate                         0                0
kaon_role                            K1               K2
track_idx                           653              655
phi_fit_pass                          1                1
phi_commonAssocPVPass                 1                1
phi_commonAssocPVIdx                  0                0
phi_trackPVPass                       1                1
phi_vertexCriteriaPass                1                1
phi_maxAbsDzPV                 0.005923         0.005923
phi_maxAbsDxyPV                0.004712         0.004712
pt                             1.380859         1.766602
eta                            0.572405         0.465651
phi                           -1.676718        -1.613922
vertexId                              0                0
fromPV                                3                3
pvAssocQuality                        7                7
hasAssocPV                            1                1
passDzPV                              1                1
passDxyPV                             1                1
passTrackPV                           1                1
dzPV                          -0.005923        -0.000209
dxyPV                          0.004712        -0.000123
dzAssocPV                     -0.005923        -0.000209
dxyAssocPV                     0.004712        -0.000123
gen_match_idx                        18               17
gen_match_source          phiMotherChi2    phiMotherChi2
gen_match_chi2                 5.115911         1.528095
matched_particle                     K-               K+
matched_phi_gen_idx                  12               12
matched_phi_particle                phi              phi
gen_chain               18:K- <- 12:phi  17:K+ <- 12:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,8.649574,-1.410955,2.801662,3.096900
1,1,5,443,J/psi,23,-1,21,21,8.649574,1.839946,-0.339931,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,13.170243,-1.022954,-3.094818,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,8.498472,1.794443,-0.365273,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,13.455444,-1.012728,3.076265,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,8.464550,1.780225,-0.358620,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,13.374368,-1.000143,3.064589,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,8.957080,1.730671,-0.166946,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,13.375796,-1.000032,3.068394,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,9.002995,1.725767,-0.222586,3.127869
10,10,18,443,J/psi,2,8,443,J/psi,13.047366,-1.018072,3.005603,3.096900
11,11,19,443,J/psi,2,9,443,J/psi,9.650789,1.657283,-0.311283,3.127869
12,12,26,333,phi,2,-1,2212,2212,3.149077,0.512985,-1.641919,1.008902
13,13,31,13,mu-,1,10,443,J/psi,8.449192,-0.952605,-3.106406,0.105658
14,14,32,-13,mu+,1,10,443,J/psi,4.936141,-1.073522,2.709732,0.105658
15,15,33,13,mu-,1,11,443,J/psi,5.407872,1.467517,-0.562744,0.105658
16,16,34,-13,mu+,1,11,443,J/psi,4.613581,1.779420,-0.015324,0.105658
17,17,37,321,K+,1,12,333,phi,1.757142,0.466408,-1.614761,0.493680
18,18,38,-321,K-,1,12,333,phi,1.393401,0.569807,-1.676169,0.493680

{'entry': 71, 'run': 1, 'lumi': 1, 'event': 9, 'nMu': 5}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,16.620415,0.900411,-1.179686,0,14,patRef,2.074868,-13.0,mu+,J/psi,9.0,16.577183
1,1,1,6.817462,2.096199,2.073822,1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
2,2,1,5.343145,1.383929,1.905803,0,12,patRef,8.030670,-13.0,mu+,J/psi,8.0,5.257142
3,3,-1,4.037060,0.917860,-0.797306,0,13,patRef,5.407825,13.0,mu-,J/psi,9.0,4.025846
4,4,-1,3.610640,1.980147,1.538903,0,11,patRef,0.611620,13.0,mu-,J/psi,8.0,3.638536

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
phi_candidate,0,1,2,3,4,5,6,7,8,9,...,2,3,4,5,6,7,8,9,10,11
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K1,K1,...,K2,K2,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,800,800,801,801,801,801,859,859,894,894,...,802,802,948,948,897,897,948,948,961,961
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,1,1,1,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
phi_commonAssocPVIdx,0,0,0,0,-1,-1,-1,-1,-1,-1,...,0,0,-1,-1,-1,-1,-1,-1,-1,-1
phi_trackPVPass,1,1,1,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
phi_vertexCriteriaPass,1,1,1,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
phi_maxAbsDzPV,0.008389,0.008389,0.006411,0.006411,3.104402,3.104402,2.726829,2.726829,3.104402,3.104402,...,0.006411,0.006411,3.104402,3.104402,2.726829,2.726829,3.104402,3.104402,10.50018,10.50018
phi_maxAbsDxyPV,0.003323,0.003323,0.00418,0.00418,3.596709,3.596709,0.029892,0.029892,3.596709,3.596709,...,0.00418,0.00418,3.596709,3.596709,0.029892,0.029892,3.596709,3.596709,0.275573,0.275573
pt,1.320312,1.320312,2.107422,2.107422,2.107422,2.107422,2.037109,2.037109,1.897461,1.897461,...,1.350586,1.350586,1.029297,1.029297,1.728516,1.728516,1.029297,1.029297,1.101562,1.101562
eta,-1.181066,-1.181066,-1.206885,-1.206885,-1.206885,-1.206885,-2.028138,-2.028138,-0.993561,-0.993561,...,-1.259987,-1.259987,-1.171545,-1.171545,-1.9494,-1.9494,-1.171545,-1.171545,-2.038759,-2.038759
phi,2.667652,2.667652,2.66619,2.66619,2.66619,2.66619,0.820245,0.820245,1.943326,1.943326,...,2.879182,2.879182,2.309065,2.309065,1.032741,1.032741,2.309065,2.309065,-2.18279,-2.18279
vertexId,0,0,0,0,0,0,3,3,6,6,...,0,0,17,17,6,6,17,17,32,32
fromPV,3,3,3,3,3,3,1,1,1,1,...,3,3,1,1,1,1,1,1,1,1
pvAssocQuality,7,7,7,7,7,7,5,5,5,5,...,7,7,1,1,5,5,1,1,5,5
hasAssocPV,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,1,1,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
passDxyPV,1,1,1,1,1,1,1,1,0,0,...,1,1,0,0,1,1,0,0,1,1
passTrackPV,1,1,1,1,1,1,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
dzPV,0.008389,0.008389,-0.002712,-0.002712,-0.002712,-0.002712,-2.650158,-2.650158,-2.825459,-2.825459,...,-0.006411,-0.006411,-3.104402,-3.104402,-2.726829,-2.726829,-3.104402,-3.104402,-8.560335,-8.560335
dxyPV,-0.000334,-0.000334,0.003323,0.003323,0.003323,0.003323,0.028413,0.028413,-0.38027,-0.38027,...,0.00418,0.00418,3.596709,3.596709,-0.029892,-0.029892,3.596709,3.596709,0.042982,0.042982
dzAssocPV,0.008389,0.008389,-0.002712,-0.002712,-0.002712,-0.002712,0.05582,0.05582,-0.087031,-0.087031,...,-0.006411,-0.006411,0.026738,0.026738,0.011201,0.011201,0.026738,0.026738,0.015234,0.015234
dxyAssocPV,-0.000334,-0.000334,0.003323,0.003323,0.003323,0.003323,0.028164,0.028164,-0.380625,-0.380625,...,0.00418,0.00418,3.5925,3.5925,-0.03125,-0.03125,3.5925,3.5925,0.039844,0.039844
gen_match_idx,16,16,15,15,15,15,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
gen_match_source,phiMotherChi2,phiMotherChi2,phiMotherChi2,phiMotherChi2,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,...,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,0.228961,0.228961,4.160378,4.160378,4.160378,4.160378,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
matched_particle,K-,K-,K+,K+,K+,K+,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
matched_phi_gen_idx,10,10,10,10,10,10,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
matched_phi_particle,phi,phi,phi,phi,phi,phi,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
gen_chain,16:K- <- 10:phi,16:K- <- 10:phi,15:K+ <- 10:phi,15:K+ <- 10:phi,15:K+ <- 10:phi,15:K+ <- 10:phi,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,12.230382,1.812385,1.859504,3.096900
1,1,5,443,J/psi,23,-1,21,21,12.230382,0.702653,-1.282089,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,10.392844,1.532994,1.708061,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,18.710127,0.963904,-1.027618,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,8.587363,1.728738,1.775254,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,20.226162,0.891031,-1.090626,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,8.473584,1.713791,1.778151,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,20.735352,0.910543,-1.103623,3.127869
8,8,16,443,J/psi,2,6,443,J/psi,8.750912,1.683981,1.757083,3.096900
9,9,17,443,J/psi,2,7,443,J/psi,20.366400,0.912044,-1.105411,3.127869
10,10,21,333,phi,2,-1,2212,2212,3.487601,-1.197680,2.666900,1.021350
11,11,32,13,mu-,1,8,443,J/psi,3.638536,1.979921,1.539522,0.105658
12,12,33,-13,mu+,1,8,443,J/psi,5.257142,1.384215,1.907035,0.105658
13,13,34,13,mu-,1,9,443,J/psi,4.025846,0.917098,-0.795956,0.105658
14,14,35,-13,mu+,1,9,443,J/psi,16.577183,0.900458,-1.179438,0.105658
15,15,36,321,K+,1,10,333,phi,2.171722,-1.207525,2.666853,0.493680
16,16,37,-321,K-,1,10,333,phi,1.315879,-1.181254,2.666977,0.493680

{'entry': 72, 'run': 1, 'lumi': 1, 'event': 26, 'nMu': 8}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,6.080385,-2.053520,0.331433,7,11,patRef,8.225039,13.0,mu-,J/psi,7.0,6.260969
1,1,-1,3.856990,1.912183,-2.375876,0,9,patRef,2.703414,13.0,mu-,J/psi,6.0,3.808725
2,2,1,3.827051,2.312195,-3.095331,0,10,patRef,4.902075,-13.0,mu+,J/psi,6.0,3.804284
3,3,1,3.161234,-1.450517,0.667202,0,12,patRef,0.320217,-13.0,mu+,J/psi,7.0,3.179622
4,4,1,2.207174,-2.457212,1.271512,2,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,-1,1.664586,-2.210039,1.795302,3,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,-1,1.203132,-1.818855,-3.116936,0,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
7,7,1,1.028729,-2.057696,2.664085,0,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
phi_candidate,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,719,725,726,733,733,780,791,791,845,873,854,879,728,734,863,860,845,867,851,879
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
phi_commonAssocPVIdx,-1,-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,-1
phi_trackPVPass,0,1,1,1,0,0,1,1,0,0,0,1,1,1,0,0,1,1,0,0
phi_vertexCriteriaPass,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
phi_maxAbsDzPV,2.207874,1.713403,0.00873,0.002081,3.202126,2.488416,1.201794,1.201794,2.128101,2.050107,2.207874,1.713403,0.00873,0.002081,3.202126,2.488416,1.201794,1.201794,2.128101,2.050107
phi_maxAbsDxyPV,5.67,0.005654,0.002084,0.012334,0.635736,0.087407,0.01804,0.001362,0.01804,1.168531,5.67,0.005654,0.002084,0.012334,0.635736,0.087407,0.01804,0.001362,0.01804,1.168531
pt,1.020508,1.52832,1.512695,1.561523,1.561523,1.313477,1.227539,1.227539,1.004883,1.157227,1.101562,1.286133,1.283203,2.488281,1.579102,1.107422,1.004883,1.756836,1.295898,1.286133
eta,0.314219,1.781304,1.77691,0.398267,0.398267,0.067385,2.437025,2.437025,2.437757,1.099765,-0.122868,1.40025,1.554796,0.349742,0.222663,0.52974,2.437757,2.434095,2.071535,1.40025
phi,-0.32295,2.398211,-2.99502,2.847737,2.847737,2.166172,1.923114,1.923114,1.815104,2.482196,0.140034,2.506432,-3.103407,2.898335,3.049013,2.218516,1.815104,2.155822,1.836489,2.506432
vertexId,0,0,0,0,0,3,4,4,9,16,10,18,0,0,12,11,9,14,10,18
fromPV,2,3,3,3,3,1,1,1,1,1,1,1,3,2,1,1,1,1,1,1
pvAssocQuality,1,7,7,7,7,5,0,0,1,5,5,7,7,6,1,5,1,5,0,7
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,1,1,1,1,1,0,1,1,1,0,0,1,1,1,0,1,1,1,0,1
passDxyPV,0,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1
passTrackPV,0,1,1,1,1,0,1,1,1,0,0,1,1,1,0,1,1,1,0,1
dzPV,0.31625,-0.003635,-0.008115,-0.001892,-0.001892,2.488416,1.201794,1.201794,0.877858,-2.050107,2.207874,-1.713403,0.00873,-0.002081,3.202126,1.090663,0.877858,1.017956,2.128101,-1.713403
dxyPV,-5.67,0.003621,0.001329,0.000526,0.000526,0.087407,-0.000677,-0.000677,0.01804,-1.168531,-0.0168,0.005654,0.002084,0.012334,-0.635736,-0.044619,0.01804,-0.001362,0.003848,0.005654
dzAssocPV,0.31625,-0.003635,-0.008115,-0.001892,-0.001892,-0.031934,0.068203,0.068203,0.083125,0.051875,-0.029707,-0.00176,0.00873,-0.002081,0.267969,0.015498,0.083125,-0.043164,-0.106797,-0.00176
dxyAssocPV,-5.67,0.003621,0.001329,0.000526,0.000526,0.088047,-0.000731,-0.000731,0.018281,-1.188125,-0.017539,0.00478,0.002084,0.012334,-0.635938,-0.045781,0.018281,0.00771,0.004431,0.00478
gen_match_idx,-1,-1,-1,15,15,-1,-1,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1
gen_match_source,unmatched,unmatched,unmatched,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,-1.0,0.260461,0.260461,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,9.925957,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
matched_particle,None,None,None,K-,K-,None,None,None,None,None,None,None,None,K+,None,None,None,None,None,None
matched_phi_gen_idx,-1,-1,-1,8,8,-1,-1,-1,-1,-1,-1,-1,-1,8,-1,-1,-1,-1,-1,-1
matched_phi_particle,None,None,None,phi,phi,None,None,None,None,None,None,None,None,phi,None,None,None,None,None,None
gen_chain,None,None,None,15:K- <- 8:phi,15:K- <- 8:phi,None,None,None,None,None,None,None,None,14:K+ <- 8:phi,None,None,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,5.204161,2.519170,-2.962971,3.096900
1,1,5,443,J/psi,23,-1,21,21,5.204161,-2.492346,0.178622,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,5.180704,2.511977,-2.966809,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,8.129057,-2.051399,0.454595,3.127869
4,4,14,443,J/psi,44,2,443,J/psi,5.132189,2.527533,-2.605956,3.096900
5,5,15,443,J/psi,44,3,443,J/psi,8.126585,-2.045023,0.450347,3.127869
6,6,21,443,J/psi,2,4,443,J/psi,7.124392,2.195503,-2.737186,3.096900
7,7,22,443,J/psi,2,5,443,J/psi,9.322477,-1.899235,0.444129,3.127869
8,8,38,333,phi,2,-1,2212,2212,4.022715,0.368015,2.880421,1.019913
9,9,70,13,mu-,1,6,443,J/psi,3.808725,1.912006,-2.377182,0.105658
10,10,71,-13,mu+,1,6,443,J/psi,3.804284,2.311510,-3.097629,0.105658
11,11,72,13,mu-,1,7,443,J/psi,6.260969,-2.054932,0.331688,0.105658
12,12,73,-13,mu+,1,7,443,J/psi,3.179622,-1.450266,0.666907,0.105658
13,13,74,-421,-421,2,-1,-413,-413,0.443001,-1.741560,1.124812,1.864860
14,14,78,321,K+,1,8,333,phi,2.464600,0.348777,2.900885,0.493680
15,15,79,-321,K-,1,8,333,phi,1.559447,0.397855,2.848075,0.493680
16,16,110,13,mu-,1,13,-421,-421,0.261042,0.269854,1.970261,0.105658

{'entry': 83, 'run': 1, 'lumi': 1, 'event': 23, 'nMu': 6}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,10.904308,-2.000816,0.749487,0,13,patRef,2.367450,13.0,mu-,J/psi,10.0,10.869177
1,1,1,5.518755,-1.618078,0.882100,0,14,patRef,15.061810,-13.0,mu+,J/psi,10.0,5.283014
2,2,-1,4.881699,2.277146,-1.108046,0,15,patRef,3.136708,13.0,mu-,J/psi,11.0,4.685414
3,3,1,2.656933,2.316927,-2.013862,0,16,patRef,4.664849,-13.0,mu+,J/psi,11.0,2.724387
4,4,-1,1.056867,-2.279674,-1.415891,3,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
5,5,1,1.000538,2.061116,-0.076605,14,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9
phi_candidate,0,1,2,3,4,0,1,2,3,4
kaon_role,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2
track_idx,916,918,923,1054,1109,1117,920,924,1117,1117
phi_fit_pass,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,1,0,0,0,0,1,0,0
phi_commonAssocPVIdx,-1,-1,0,-1,-1,-1,-1,0,-1,-1
phi_trackPVPass,0,0,1,0,0,0,0,1,0,0
phi_vertexCriteriaPass,0,0,1,0,0,0,0,1,0,0
phi_maxAbsDzPV,23.870358,11.195786,0.004436,13.657596,11.556705,23.870358,11.195786,0.004436,13.657596,11.556705
phi_maxAbsDxyPV,2.223374,2.542801,0.002681,0.30376,0.929244,2.223374,2.542801,0.002681,0.30376,0.929244
pt,1.007812,1.705078,1.800781,1.391602,1.574219,1.056641,1.722656,1.52832,1.056641,1.056641
eta,-0.151982,-0.017396,-1.33195,-0.226691,0.072878,-0.289499,-0.134404,-1.448408,-0.289499,-0.289499
phi,2.848925,-0.890072,-1.024831,2.435614,2.364812,2.429673,-0.933726,-1.130119,2.429673,2.429673
vertexId,27,29,0,8,22,29,0,0,29,29
fromPV,1,1,3,1,1,1,3,3,1,1
pvAssocQuality,1,1,7,1,5,1,7,7,1,1
hasAssocPV,1,1,1,1,1,1,1,1,1,1
passDzPV,0,0,1,0,0,0,1,1,0,0
passDxyPV,0,0,1,1,0,0,1,1,0,0
passTrackPV,0,0,1,0,0,0,1,1,0,0
dzPV,23.870358,11.195786,0.004436,13.657596,11.556705,11.10859,0.001898,-0.000022,11.10859,11.10859
dxyPV,-2.223374,2.542801,0.002681,-0.023993,0.929244,0.30376,0.006143,0.001602,0.30376,0.30376
dzAssocPV,-0.016709,-0.01792,0.004436,-0.035605,-0.087422,-0.110313,0.001898,-0.000022,-0.110313,-0.110313
dxyAssocPV,-2.22375,2.5125,0.002681,-0.020332,0.914375,0.3375,0.006143,0.001602,0.3375,0.3375
gen_match_idx,-1,-1,18,-1,-1,-1,-1,17,-1,-1
gen_match_source,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,0.516543,-1.0,-1.0,-1.0,-1.0,1.76438,-1.0,-1.0
matched_particle,None,None,K-,None,None,None,None,K+,None,None
matched_phi_gen_idx,-1,-1,12,-1,-1,-1,-1,12,-1,-1
matched_phi_particle,None,None,phi,None,None,None,None,phi,None,None
gen_chain,None,None,18:K- <- 12:phi,None,None,None,None,17:K+ <- 12:phi,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,8.808919,-2.404724,1.205189,3.096900
1,1,5,443,J/psi,23,-1,21,21,8.808919,2.207299,-1.936404,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,15.601061,-1.896926,1.060116,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,8.735010,2.136876,-1.933524,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,16.160931,-1.877340,0.782391,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,8.743089,2.121897,-1.927943,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,16.262047,-1.880281,0.777552,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,7.774295,2.242215,-1.497401,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,16.270344,-1.880268,0.776681,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,7.941927,2.221373,-1.441666,3.127869
10,10,18,443,J/psi,2,8,443,J/psi,16.120222,-1.892689,0.792813,3.096900
11,11,19,443,J/psi,2,9,443,J/psi,6.722422,2.388070,-1.432386,3.127869
12,12,26,333,phi,2,-1,2212,2212,3.295860,-1.388589,-1.073437,1.021250
13,13,39,13,mu-,1,10,443,J/psi,10.869177,-2.001268,0.748969,0.105658
14,14,40,-13,mu+,1,10,443,J/psi,5.283014,-1.618860,0.883112,0.105658
15,15,41,13,mu-,1,11,443,J/psi,4.685414,2.277099,-1.108623,0.105658
16,16,42,-13,mu+,1,11,443,J/psi,2.724387,2.318473,-2.011319,0.105658
17,17,43,321,K+,1,12,333,phi,1.503778,-1.449480,-1.130655,0.493680
18,18,44,-321,K-,1,12,333,phi,1.796602,-1.332647,-1.025552,0.493680

{'entry': 86, 'run': 1, 'lumi': 1, 'event': 11, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,9.865150,2.271866,0.577400,0,20,patRef,5.968915,-13,mu+,J/psi,15,9.499931
1,1,-1,6.880391,-0.361848,2.368789,0,17,patRef,1.444699,13,mu-,J/psi,14,6.834860
2,2,1,6.113118,-0.769432,2.615425,0,18,patRef,1.013284,-13,mu+,J/psi,14,6.104751
3,3,-1,2.880426,1.997732,0.042305,0,19,patRef,0.137403,13,mu-,J/psi,15,2.876659

                                      0                1
phi_candidate                         0                0
kaon_role                            K1               K2
track_idx                           404              405
phi_fit_pass                          1                1
phi_commonAssocPVPass                 1                1
phi_commonAssocPVIdx                  0                0
phi_trackPVPass                       1                1
phi_vertexCriteriaPass                1                1
phi_maxAbsDzPV                 0.009595         0.009595
phi_maxAbsDxyPV                0.005537         0.005537
pt                             1.964844         1.612305
eta                           -0.759728        -0.802026
phi                           -1.655329        -1.536467
vertexId                              0                0
fromPV                                3                3
pvAssocQuality                        7                7
hasAssocPV                            1                1
passDzPV                              1                1
passDxyPV                             1                1
passTrackPV                           1                1
dzPV                          -0.009595         0.004885
dxyPV                          -0.00076        -0.005537
dzAssocPV                     -0.009595         0.004885
dxyAssocPV                     -0.00076        -0.005537
gen_match_idx                        22               21
gen_match_source          phiMotherChi2    phiMotherChi2
gen_match_chi2                 8.258017         3.680453
matched_particle                     K-               K+
matched_phi_gen_idx                  16               16
matched_phi_particle                phi              phi
gen_chain               22:K- <- 16:phi  21:K+ <- 16:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,9.287987,-0.872035,3.099745,3.096900
1,1,5,443,J/psi,23,-1,21,21,9.287987,2.507077,-0.041847,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,13.073288,-0.556746,2.495280,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,9.237351,2.478664,-0.011837,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,13.146677,-0.537827,2.475290,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,11.219685,2.307981,0.313101,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,12.791156,-0.566249,2.494106,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,11.219691,2.306808,0.311077,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,12.859950,-0.567013,2.478056,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,13.409320,2.132709,0.504835,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,12.889698,-0.569162,2.484509,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,12.099369,2.235521,0.498134,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,12.875395,-0.568110,2.484967,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,12.107167,2.234887,0.479126,3.127869
14,14,23,443,J/psi,2,12,443,J/psi,12.841736,-0.568317,2.485229,3.096900
15,15,24,443,J/psi,2,13,443,J/psi,12.063653,2.238623,0.455522,3.127869
16,16,30,333,phi,2,-1,2212,2212,3.538851,-0.781056,-1.601901,1.013561
17,17,44,13,mu-,1,14,443,J/psi,6.834860,-0.361625,2.368948,0.105658
18,18,45,-13,mu+,1,14,443,J/psi,6.104751,-0.769055,2.615490,0.105658
19,19,46,13,mu-,1,15,443,J/psi,2.876659,1.997202,0.042083,0.105658
20,20,47,-13,mu+,1,15,443,J/psi,9.499931,2.271051,0.577480,0.105658
21,21,51,321,K+,1,16,333,phi,1.623197,-0.800850,-1.538269,0.493680
22,22,52,-321,K-,1,16,333,phi,1.921712,-0.762050,-1.655638,0.493680

{'entry': 87, 'run': 1, 'lumi': 1, 'event': 43, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,6.782591,1.060052,-1.000135,0,15,patRef,1.435990,-13,mu+,J/psi,12,6.730901
1,1,-1,3.581909,1.023635,-1.648227,0,14,patRef,9.267170,13,mu-,J/psi,12,3.471395
2,2,-1,3.124210,2.197185,2.777881,0,16,patRef,0.785655,13,mu-,J/psi,13,3.168100
3,3,1,2.635399,1.929093,1.685937,0,17,patRef,1.665695,-13,mu+,J/psi,13,2.668557

                                0                1          2                3
phi_candidate                   0                1          0                1
kaon_role                      K1               K1         K2               K2
track_idx                     384              425        430              426
phi_fit_pass                    1                1          1                1
phi_commonAssocPVPass           0                1          0                1
phi_commonAssocPVIdx           -1                7         -1                7
phi_trackPVPass                 0                1          0                1
phi_vertexCriteriaPass          0                1          0                1
phi_maxAbsDzPV           1.644458         0.071034   1.644458         0.071034
phi_maxAbsDxyPV           0.66375         0.015484    0.66375         0.015484
pt                       1.461914         1.300781   1.605469         1.751953
eta                       2.10303        -1.283792   2.140934        -1.381939
phi                     -2.012457         1.417907  -2.317447         1.452285
vertexId                        0                7          9                7
fromPV                          2                1          1                1
pvAssocQuality                  1                7          5                7
hasAssocPV                      1                1          1                1
passDzPV                        1                1          1                1
passDxyPV                       0                1          1                1
passTrackPV                     0                1          1                1
dzPV                     0.201719        -0.043312   1.644458        -0.071034
dxyPV                     0.66375        -0.013102    0.00497        -0.015484
dzAssocPV                0.201719         0.014463  -0.039629        -0.012881
dxyAssocPV                0.66375         0.001371   0.003184        -0.000925
gen_match_idx                  -1               23         -1               22
gen_match_source        unmatched    phiMotherChi2  unmatched    phiMotherChi2
gen_match_chi2               -1.0         3.057382       -1.0         6.553643
matched_particle             None               K-       None               K+
matched_phi_gen_idx            -1               21         -1               21
matched_phi_particle         None              phi       None              phi
gen_chain                    None  23:K- <- 21:phi       None  22:K+ <- 21:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,6.382539,0.933866,-0.956183,3.096900
1,1,5,443,J/psi,23,-1,21,21,6.382539,2.263267,2.185410,3.127869
2,2,11,443,J/psi,44,0,443,J/psi,9.429689,1.143926,-1.254376,3.096900
3,3,12,443,J/psi,44,1,443,J/psi,5.714318,2.106047,2.318203,3.127869
4,4,14,443,J/psi,44,2,443,J/psi,9.423038,1.134685,-1.250887,3.096900
5,5,15,443,J/psi,44,3,443,J/psi,5.712238,2.097277,2.316641,3.127869
6,6,19,443,J/psi,44,4,443,J/psi,9.334766,1.125799,-1.245167,3.096900
7,7,20,443,J/psi,44,5,443,J/psi,5.728251,2.097842,2.312581,3.127869
8,8,24,443,J/psi,44,6,443,J/psi,9.335256,1.125273,-1.245559,3.096900
9,9,25,443,J/psi,44,7,443,J/psi,5.728534,2.097305,2.312750,3.127869
10,10,28,443,J/psi,44,8,443,J/psi,9.742564,1.082671,-1.217557,3.096900
11,11,29,443,J/psi,44,9,443,J/psi,4.957520,2.241861,2.284737,3.127869
12,12,32,443,J/psi,2,10,443,J/psi,9.725167,1.085626,-1.217623,3.096900
13,13,33,443,J/psi,2,11,443,J/psi,4.994360,2.234018,2.283454,3.127869
14,14,46,13,mu-,1,12,443,J/psi,3.471395,1.023102,-1.649352,0.105658
15,15,47,-13,mu+,1,12,443,J/psi,6.730901,1.060468,-1.000105,0.105658
16,16,48,13,mu-,1,13,443,J/psi,3.168100,2.196536,2.777625,0.105658
17,17,49,-13,mu+,1,13,443,J/psi,2.668557,1.927881,1.685334,0.105658
18,18,54,411,411,2,-1,521,521,0.548233,-3.700130,-0.011068,1.869620
19,19,60,-13,mu+,1,18,411,411,0.299699,-2.972409,2.555307,0.105658
20,20,62,-321,K-,1,18,411,411,0.690379,-2.567243,0.564909,0.493680
21,21,68,333,phi,2,-1,431,431,3.078849,-1.344637,1.436095,1.019480
22,22,75,321,K+,1,21,333,phi,1.781483,-1.385169,1.450642,0.493680
23,23,76,-321,K-,1,21,333,phi,1.297814,-1.286243,1.416125,0.493680

{'entry': 88, 'run': 1, 'lumi': 1, 'event': 79, 'nMu': 9}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,34.769463,-1.150806,-1.940753,-1,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
1,1,1,5.149493,2.282662,3.064797,0,26,patRef,7.359330,-13.0,mu+,J/psi,21.0,5.250527
2,2,1,4.787925,-1.976508,-0.225758,0,24,patRef,0.880611,-13.0,mu+,J/psi,20.0,4.747250
3,3,-1,4.446716,-1.425005,0.147373,0,23,patRef,0.764956,13.0,mu-,J/psi,20.0,4.468699
4,4,-1,3.397287,2.380799,-2.464084,0,25,patRef,2.308981,13.0,mu-,J/psi,21.0,3.364282
5,5,-1,1.904405,-1.519226,-0.317783,9,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
6,6,1,1.790102,2.324362,-0.810682,5,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
7,7,-1,1.135453,-2.151514,2.747439,8,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN
8,8,1,1.060697,2.028382,-2.874234,4,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5
phi_candidate,0,1,2,0,1,2
kaon_role,K1,K1,K1,K2,K2,K2
track_idx,703,705,708,812,744,709
phi_fit_pass,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,1,0,0,1
phi_commonAssocPVIdx,-1,-1,0,-1,-1,0
phi_trackPVPass,0,0,1,0,0,1
phi_vertexCriteriaPass,0,0,1,0,0,1
phi_maxAbsDzPV,21.220304,5.528051,0.012646,21.220304,5.528051,0.012646
phi_maxAbsDxyPV,2.888258,2.716443,0.001571,2.888258,2.716443,0.001571
pt,1.011719,1.136719,2.035156,1.349609,1.495117,1.226562
eta,-1.588855,-2.124454,0.353771,-1.814631,-1.70275,0.308359
phi,0.424241,-1.018887,1.444385,0.848261,-0.798455,1.425833
vertexId,8,22,0,15,2,0
fromPV,1,1,3,1,1,3
pvAssocQuality,1,1,7,5,5,7
hasAssocPV,1,1,1,1,1,1
passDzPV,0,0,1,0,0,1
passDxyPV,0,0,1,0,1,1
passTrackPV,0,0,1,0,0,1
dzPV,-21.220304,2.565778,-0.001709,4.822606,5.528051,0.012646
dxyPV,2.888258,-2.716443,-0.001245,-0.420079,-0.016507,0.001571
dzAssocPV,-20.469999,0.104063,-0.001709,-0.0875,-0.055078,0.012646
dxyAssocPV,2.885,-2.715,-0.001245,-0.423125,-0.01667,0.001571
gen_match_idx,-1,-1,28,-1,-1,27
gen_match_source,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,phiMotherChi2
gen_match_chi2,-1.0,-1.0,1.13018,-1.0,-1.0,7.754266
matched_particle,None,None,K-,None,None,K+
matched_phi_gen_idx,-1,-1,22,-1,-1,22
matched_phi_particle,None,None,phi,None,None,phi
gen_chain,None,None,28:K- <- 22:phi,None,None,27:K+ <- 22:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,7.069258,-1.982211,0.358701,3.096900
1,1,5,443,J/psi,23,-1,21,21,7.069258,2.554434,-2.782891,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,7.063573,-1.874984,0.354602,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,7.859139,2.554586,-2.488682,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,6.368255,-2.062284,-0.259093,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,7.902868,2.475446,-2.482959,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,4.138331,-2.558392,-0.048791,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,7.914018,2.411676,-2.487532,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,7.485714,-1.977055,-0.042717,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,7.874609,2.396738,-2.483401,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,7.459826,-1.957166,-0.040408,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,8.761807,2.307316,-2.729989,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,8.952332,-1.779842,-0.083529,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,8.740208,2.300386,-2.727879,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,8.945597,-1.771885,-0.081325,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,8.626512,2.320807,-2.851662,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,8.951791,-1.772350,-0.079902,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,8.103745,2.383407,-2.913248,3.127869
18,18,26,443,J/psi,44,16,443,J/psi,8.806212,-1.788758,-0.106020,3.096900
19,19,27,443,J/psi,44,17,443,J/psi,8.107176,2.383707,-2.912900,3.127869
20,20,28,443,J/psi,2,18,443,J/psi,9.056660,-1.760861,-0.045127,3.096900
21,21,29,443,J/psi,2,19,443,J/psi,8.039913,2.390600,-2.929267,3.127869
22,22,37,333,phi,2,-1,2212,2212,3.252330,0.337856,1.437405,1.019067
23,23,45,13,mu-,1,20,443,J/psi,4.468699,-1.424981,0.146849,0.105658
24,24,46,-13,mu+,1,20,443,J/psi,4.747250,-1.977058,-0.225711,0.105658
25,25,47,13,mu-,1,21,443,J/psi,3.364282,2.380169,-2.465812,0.105658
26,26,48,-13,mu+,1,21,443,J/psi,5.250527,2.284208,3.063407,0.105658
27,27,49,321,K+,1,22,333,phi,1.232836,0.312046,1.426192,0.493680
28,28,50,-321,K-,1,22,333,phi,2.019619,0.353486,1.444250,0.493680

{'entry': 96, 'run': 1, 'lumi': 1, 'event': 19, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,5.113747,1.255354,-2.773555,0,10,patRef,6.361335,-13,mu+,J/psi,5,5.271971
1,1,1,4.072792,-1.343989,1.307813,0,8,patRef,1.345664,-13,mu+,J/psi,4,4.026187
2,2,-1,4.011334,-2.027653,0.999509,0,7,patRef,1.323902,13,mu-,J/psi,4,4.096311
3,3,-1,3.666754,1.900224,-2.510278,0,9,patRef,1.200868,13,mu-,J/psi,5,3.697547

                                0               1          2               3
phi_candidate                   0               1          0               1
kaon_role                      K1              K1         K2              K2
track_idx                     701             706        703             707
phi_fit_pass                    1               1          1               1
phi_commonAssocPVPass           0               1          0               1
phi_commonAssocPVIdx           -1               0         -1               0
phi_trackPVPass                 0               1          0               1
phi_vertexCriteriaPass          0               1          0               1
phi_maxAbsDzPV            3.36321        0.035625    3.36321        0.035625
phi_maxAbsDxyPV          1.666714        0.014736   1.666714        0.014736
pt                       1.331055        1.499023   1.462891        2.105469
eta                      1.639027        2.017334   1.662099        1.958373
phi                     -1.458255       -0.421588   -1.04231       -0.325796
vertexId                        9               0         16               0
fromPV                          1               3          1               2
pvAssocQuality                  1               7          1               6
hasAssocPV                      1               1          1               1
passDzPV                        1               1          0               1
passDxyPV                       0               1          0               1
passTrackPV                     0               1          0               1
dzPV                    -0.914394       -0.035625   -3.36321        0.027734
dxyPV                   -0.120236       -0.000954  -1.666714       -0.014736
dzAssocPV               -0.011475       -0.035625  -0.339687        0.027734
dxyAssocPV              -0.117656       -0.000954   -1.66375       -0.014736
gen_match_idx                  -1              11         -1              12
gen_match_source        unmatched   phiMotherChi2  unmatched   phiMotherChi2
gen_match_chi2               -1.0        2.050879       -1.0        3.359305
matched_particle             None              K+       None              K-
matched_phi_gen_idx            -1               6         -1               6
matched_phi_particle         None             phi       None             phi
gen_chain                    None  11:K+ <- 6:phi       None  12:K- <- 6:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,6.484756,-2.001240,0.924103,3.096900
1,1,5,443,J/psi,23,-1,21,21,6.484756,1.871893,-2.217489,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,6.452089,-1.973940,0.941850,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,9.032115,1.564775,-2.742368,3.127869
4,4,12,443,J/psi,2,2,443,J/psi,8.026417,-1.753456,1.152212,3.096900
5,5,13,443,J/psi,2,3,443,J/psi,8.893538,1.576152,-2.665079,3.127869
6,6,19,333,phi,2,-1,2212,2212,3.611751,1.983545,-0.366388,1.016746
7,7,22,13,mu-,1,4,443,J/psi,4.096311,-2.027190,0.999581,0.105658
8,8,23,-13,mu+,1,4,443,J/psi,4.026187,-1.344508,1.307522,0.105658
9,9,24,13,mu-,1,5,443,J/psi,3.697547,1.900091,-2.509402,0.105658
10,10,25,-13,mu+,1,5,443,J/psi,5.271971,1.255602,-2.774040,0.105658
11,11,26,321,K+,1,6,333,phi,1.489678,2.014442,-0.420685,0.493680
12,12,27,-321,K-,1,6,333,phi,2.125806,1.959604,-0.328349,0.493680

{'entry': 100, 'run': 1, 'lumi': 1, 'event': 16, 'nMu': 5}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,6.389839,1.313350,2.431813,0,25,patRef,1.987852,-13.0,mu+,J/psi,20.0,6.276585
1,1,1,6.062748,-0.500468,-0.827837,0,27,patRef,0.283849,-13.0,mu+,J/psi,21.0,6.056432
2,2,-1,3.326091,1.750447,1.919060,0,24,patRef,0.780066,13.0,mu-,J/psi,20.0,3.363441
3,3,-1,3.122272,-1.161533,-1.079032,4,26,patRef,5.460061,13.0,mu-,J/psi,21.0,3.107375
4,4,1,0.910382,-2.149265,0.561662,9,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
phi_candidate,0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,1098,1106,1107,1111,1114,1120,1130,1200,1113,1374,1280,1112,1115,1122,1280,1291
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0
phi_commonAssocPVIdx,-1,-1,-1,0,0,0,-1,-1,-1,-1,-1,0,0,0,-1,-1
phi_trackPVPass,0,0,0,1,1,1,0,1,0,0,0,1,1,1,0,1
phi_vertexCriteriaPass,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0
phi_maxAbsDzPV,4.451243,4.590175,0.741967,0.037422,0.009927,0.013623,0.741967,0.663031,4.451243,4.590175,0.741967,0.037422,0.009927,0.013623,0.741967,0.663031
phi_maxAbsDxyPV,0.317842,0.010608,0.164252,0.023906,0.009614,0.001832,0.164252,0.014475,0.317842,0.010608,0.164252,0.023906,0.009614,0.001832,0.164252,0.014475
pt,1.853516,1.219727,1.277344,1.082031,1.533203,2.072266,1.15332,1.087891,1.223633,1.003906,1.298828,1.322266,1.135742,1.134766,1.298828,1.586914
eta,-0.679891,2.2107,1.94995,-0.481033,-0.771264,-1.94995,2.288705,-2.414685,-0.695273,2.39967,2.311777,-0.633747,-1.034577,-2.060183,2.311777,-2.441969
phi,-1.623775,1.523785,-0.065229,2.1949,-1.021522,2.774503,-0.353633,2.286798,-1.518984,1.24956,-0.198143,1.902199,-1.361867,2.769705,-0.198143,2.570971
vertexId,22,0,0,0,0,0,1,4,0,30,9,0,0,0,9,9
fromPV,1,3,3,3,3,3,1,1,2,1,1,2,3,3,1,1
pvAssocQuality,1,7,7,7,7,7,5,0,5,1,5,1,7,7,5,1
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1
passDxyPV,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1
passTrackPV,0,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1
dzPV,4.451243,0.086094,-0.003772,-0.003826,-0.000096,-0.007656,-0.302198,-0.022476,0.042148,4.590175,-0.741967,0.037422,-0.009927,0.013623,-0.741967,-0.663031
dxyPV,-0.317842,0.005859,0.002148,0.011475,0.009614,-0.001832,-0.003989,-0.002795,-0.064766,0.010608,0.164252,0.023906,0.00522,-0.00013,0.164252,-0.014475
dzAssocPV,0.082813,0.086094,-0.003772,-0.003826,-0.000096,-0.007656,0.004116,-0.005508,0.042148,0.044102,-0.067734,0.037422,-0.009927,0.013623,-0.067734,0.014385
dxyAssocPV,-0.319219,0.005859,0.002148,0.011475,0.009614,-0.001832,-0.003367,-0.001713,-0.064766,0.010537,0.165312,0.023906,0.00522,-0.00013,0.165312,-0.014336
gen_match_idx,-1,-1,-1,-1,-1,31,-1,-1,-1,-1,-1,-1,-1,30,-1,-1
gen_match_source,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,-1.0,-1.0,-1.0,3.478903,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.81003,-1.0,-1.0
matched_particle,None,None,None,None,None,K-,None,None,None,None,None,None,None,K+,None,None
matched_phi_gen_idx,-1,-1,-1,-1,-1,23,-1,-1,-1,-1,-1,-1,-1,23,-1,-1
matched_phi_particle,None,None,None,None,None,phi,None,None,None,None,None,None,None,phi,None,None
gen_chain,None,None,None,None,None,31:K- <- 23:phi,None,None,None,None,None,None,None,30:K+ <- 23:phi,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,5.103383,2.191236,2.513481,3.096900
1,1,5,443,J/psi,23,-1,21,21,5.103383,-1.410316,-0.628112,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,4.927014,2.137346,2.533430,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,10.333755,-0.746126,-0.892423,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,4.956298,2.135655,2.533828,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,9.580922,-0.825778,-0.921410,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,7.290919,1.762612,2.248410,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,9.303396,-0.787342,-0.906008,3.127869
8,8,20,443,J/psi,44,6,443,J/psi,9.393429,1.509429,2.252983,3.096900
9,9,21,443,J/psi,44,7,443,J/psi,9.075854,-0.765990,-0.906842,3.127869
10,10,24,443,J/psi,44,8,443,J/psi,9.382116,1.510957,2.256297,3.096900
11,11,25,443,J/psi,44,9,443,J/psi,9.077146,-0.765780,-0.907211,3.127869
12,12,28,443,J/psi,44,10,443,J/psi,9.350523,1.514332,2.256082,3.096900
13,13,29,443,J/psi,44,11,443,J/psi,9.080561,-0.766099,-0.907178,3.127869
14,14,30,443,J/psi,44,12,443,J/psi,9.334052,1.516299,2.255655,3.096900
15,15,31,443,J/psi,44,13,443,J/psi,9.082335,-0.766056,-0.907127,3.127869
16,16,37,443,J/psi,44,14,443,J/psi,9.335744,1.516118,2.254647,3.096900
17,17,38,443,J/psi,44,15,443,J/psi,9.082130,-0.766037,-0.907015,3.127869
18,18,40,443,J/psi,44,16,443,J/psi,9.331013,1.516625,2.254577,3.096900
19,19,41,443,J/psi,44,17,443,J/psi,9.082642,-0.766084,-0.907006,3.127869
20,20,42,443,J/psi,2,18,443,J/psi,9.353452,1.513815,2.254696,3.096900
21,21,43,443,J/psi,2,19,443,J/psi,9.099553,-0.763695,-0.912367,3.127869
22,22,47,333,phi,2,-1,2212,2212,0.789799,-6.225349,2.248832,1.019256
23,23,58,333,phi,2,-1,2212,2212,3.176908,-1.991121,2.772147,1.025514
24,24,86,13,mu-,1,20,443,J/psi,3.363441,1.750848,1.918847,0.105658
25,25,87,-13,mu+,1,20,443,J/psi,6.276585,1.313510,2.432235,0.105658
26,26,88,13,mu-,1,21,443,J/psi,3.107375,-1.162957,-1.078022,0.105658
27,27,89,-13,mu+,1,21,443,J/psi,6.056432,-0.500522,-0.827660,0.105658
28,28,92,321,K+,1,22,333,phi,0.521859,-5.948323,2.232482,0.493680
29,29,93,-321,K-,1,22,333,phi,0.268146,-6.610708,2.280657,0.493680
30,30,99,321,K+,1,23,333,phi,1.160580,-2.058406,2.769540,0.493680
31,31,100,-321,K-,1,23,333,phi,2.016334,-1.950313,2.773647,0.493680
32,32,101,321,K+,1,-1,-411,-411,0.497991,4.135189,2.886570,0.493680

{'entry': 116, 'run': 1, 'lumi': 1, 'event': 289, 'nMu': 4}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,-1,3.866019,1.385494,2.187931,0,21,patRef,1.412232,13,mu-,J/psi,18,3.922929
1,1,-1,3.774683,-1.897151,-1.620326,0,23,patRef,4.286741,13,mu-,J/psi,19,3.718543
2,2,1,3.627292,-1.675726,-0.775394,0,24,patRef,0.232396,-13,mu+,J/psi,19,3.615972
3,3,1,3.502744,1.653676,1.374949,0,22,patRef,8.008853,-13,mu+,J/psi,18,3.497549

                                      0                1
phi_candidate                         0                0
kaon_role                            K1               K2
track_idx                           434              435
phi_fit_pass                          1                1
phi_commonAssocPVPass                 1                1
phi_commonAssocPVIdx                  0                0
phi_trackPVPass                       1                1
phi_vertexCriteriaPass                1                1
phi_maxAbsDzPV                 0.006255         0.006255
phi_maxAbsDxyPV                0.004089         0.004089
pt                              1.15625         1.888672
eta                            1.499496         1.438704
phi                            1.060473         1.033826
vertexId                              0                0
fromPV                                3                3
pvAssocQuality                        7                7
hasAssocPV                            1                1
passDzPV                              1                1
passDxyPV                             1                1
passTrackPV                           1                1
dzPV                          -0.006255         0.002168
dxyPV                         -0.004089         0.000353
dzAssocPV                     -0.006255         0.002168
dxyAssocPV                    -0.004089         0.000353
gen_match_idx                        26               25
gen_match_source          phiMotherChi2    phiMotherChi2
gen_match_chi2                 1.960379         0.114044
matched_particle                     K-               K+
matched_phi_gen_idx                  20               20
matched_phi_particle                phi              phi
gen_chain               26:K- <- 20:phi  25:K+ <- 20:phi

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,5.097759,1.884080,2.243515,3.096900
1,1,5,443,J/psi,23,-1,21,21,5.097759,-2.185050,-0.898078,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,8.015927,1.449034,1.806635,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,5.048084,-2.163287,-0.882473,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,7.021274,1.587533,1.872252,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,5.064540,-2.158710,-0.886396,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,6.945965,1.578936,1.880012,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,6.672585,-1.884085,-1.194958,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,6.747192,1.608012,1.794157,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,6.682100,-1.884961,-1.191908,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,6.837981,1.594701,1.803687,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,6.678494,-1.884560,-1.192181,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,6.836958,1.594580,1.803987,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,6.697792,-1.881694,-1.200830,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,6.826166,1.596841,1.808148,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,6.698043,-1.881040,-1.200991,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,6.819232,1.598265,1.804547,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,6.698413,-1.880671,-1.200864,3.127869
18,18,26,443,J/psi,2,16,443,J/psi,6.820640,1.598124,1.806902,3.096900
19,19,27,443,J/psi,2,17,443,J/psi,6.687916,-1.882210,-1.204467,3.127869
20,20,30,333,phi,2,-1,2212,2212,3.019844,1.461588,1.043540,1.016391
21,21,41,13,mu-,1,18,443,J/psi,3.922929,1.385640,2.187842,0.105658
22,22,42,-13,mu+,1,18,443,J/psi,3.497549,1.655275,1.376746,0.105658
23,23,43,13,mu-,1,19,443,J/psi,3.718543,-1.898561,-1.621262,0.105658
24,24,44,-13,mu+,1,19,443,J/psi,3.615972,-1.675568,-0.775078,0.105658
25,25,47,321,K+,1,20,333,phi,1.882818,1.439003,1.033868,0.493680
26,26,48,-321,K-,1,20,333,phi,1.137260,1.497822,1.059553,0.493680

{'entry': 117, 'run': 1, 'lumi': 1, 'event': 392, 'nMu': 5}

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt
0,0,1,10.515039,2.233940,0.334861,0,23,patRef,7.509422,-13.0,mu+,J/psi,18.0,9.820020
1,1,-1,5.785806,-1.390446,-2.954573,0,24,patRef,22.694853,13.0,mu-,J/psi,19.0,5.959050
2,2,1,4.774016,-0.994521,-2.523483,0,25,patRef,0.496877,-13.0,mu+,J/psi,19.0,4.789120
3,3,-1,2.830846,2.212876,0.930935,0,22,patRef,0.257882,13.0,mu-,J/psi,18.0,2.818958
4,4,1,1.730954,-2.204948,1.959815,4,-1,unmatched,-1.000000,NaN,None,None,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
phi_candidate,0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7
kaon_role,K1,K1,K1,K1,K1,K1,K1,K1,K2,K2,K2,K2,K2,K2,K2,K2
track_idx,1076,1078,1079,1080,1084,1137,1280,1280,1338,1080,1080,1083,1236,1314,1320,1344
phi_fit_pass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
phi_commonAssocPVPass,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0
phi_commonAssocPVIdx,-1,0,0,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1
phi_trackPVPass,0,1,1,0,0,0,1,0,0,1,1,0,0,0,1,0
phi_vertexCriteriaPass,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0
phi_maxAbsDzPV,33.834503,0.080469,0.027031,2.250924,5.163335,6.754766,1.625505,1.625505,33.834503,0.080469,0.027031,2.250924,5.163335,6.754766,1.625505,1.625505
phi_maxAbsDxyPV,0.481731,0.018369,0.003191,0.025195,0.010714,0.317983,0.060505,0.520719,0.481731,0.018369,0.003191,0.025195,0.010714,0.317983,0.060505,0.520719
pt,1.640625,1.013672,1.692383,2.037109,1.027344,1.244141,1.458008,1.458008,1.009766,2.037109,2.037109,1.162109,1.694336,1.009766,1.25293,1.555664
eta,-2.056703,2.460463,2.285409,2.151006,2.477126,1.274636,0.18952,0.18952,-2.421644,2.151006,2.151006,2.483718,2.409009,0.958403,0.457961,0.050722
phi,-2.630738,-2.008157,-2.167053,-2.158362,2.609367,1.897722,-2.123105,-2.123105,-2.703784,-2.158362,-2.158362,-2.065403,2.206128,2.291584,-2.136483,-2.483773
vertexId,39,0,0,0,1,3,12,12,28,0,0,1,8,18,19,30
fromPV,1,2,3,3,1,1,1,1,1,3,3,1,1,1,1,1
pvAssocQuality,1,1,7,7,0,1,1,1,1,7,7,1,1,1,5,1
hasAssocPV,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
passDzPV,0,1,1,1,0,0,1,1,0,1,1,0,0,0,1,1
passDxyPV,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0
passTrackPV,0,1,1,1,0,0,1,1,0,1,1,0,0,0,1,0
dzPV,-33.834503,-0.080469,-0.024316,-0.027031,2.336835,-6.754766,-1.625505,-1.625505,4.515185,-0.027031,-0.027031,2.250924,5.163335,-4.980865,-1.390653,-0.800623
dxyPV,0.481731,0.018369,-0.003191,-0.001906,-0.00076,-0.317983,0.060505,0.060505,-0.040062,-0.001906,-0.001906,-0.025195,0.010714,0.043951,0.053366,-0.520719
dzAssocPV,-22.6,-0.080469,-0.024316,-0.027031,-0.005024,-0.475,-0.060664,-0.060664,0.030527,-0.027031,-0.027031,-0.071172,-0.029746,-0.416562,-0.02998,0.099219
dxyAssocPV,0.470937,0.018369,-0.003191,-0.001906,-0.002871,-0.32,0.059844,0.059844,-0.054141,-0.001906,-0.001906,-0.026289,0.009785,0.046367,0.055937,-0.522812
gen_match_idx,-1,-1,26,27,-1,-1,-1,-1,-1,27,27,-1,-1,-1,-1,-1
gen_match_source,unmatched,unmatched,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched,phiMotherChi2,phiMotherChi2,unmatched,unmatched,unmatched,unmatched,unmatched
gen_match_chi2,-1.0,-1.0,5.89078,4.445002,-1.0,-1.0,-1.0,-1.0,-1.0,4.445002,4.445002,-1.0,-1.0,-1.0,-1.0,-1.0
matched_particle,None,None,K+,K-,None,None,None,None,None,K-,K-,None,None,None,None,None
matched_phi_gen_idx,-1,-1,20,20,-1,-1,-1,-1,-1,20,20,-1,-1,-1,-1,-1
matched_phi_particle,None,None,phi,phi,None,None,None,None,None,phi,phi,None,None,None,None,None
gen_chain,None,None,26:K+ <- 20:phi,27:K- <- 20:phi,None,None,None,None,None,27:K- <- 20:phi,27:K- <- 20:phi,None,None,None,None,None

,gen_idx,handle_index,pdg_id,particle,status,mother_idx,mother_pdg_id,mother,pt,eta,phi,mass
0,0,4,443,J/psi,23,-1,21,21,5.761315,3.038068,0.177543,3.096900
1,1,5,443,J/psi,23,-1,21,21,5.761315,-1.868682,-2.964050,3.127869
2,2,10,443,J/psi,44,0,443,J/psi,10.487276,2.465227,0.360558,3.096900
3,3,11,443,J/psi,44,1,443,J/psi,5.718086,-1.837957,-2.967223,3.127869
4,4,12,443,J/psi,44,2,443,J/psi,10.368895,2.450024,0.354953,3.096900
5,5,13,443,J/psi,44,3,443,J/psi,10.111302,-1.274031,-2.670669,3.127869
6,6,14,443,J/psi,44,4,443,J/psi,12.514870,2.264978,0.599833,3.096900
7,7,15,443,J/psi,44,5,443,J/psi,10.057508,-1.266407,-2.677816,3.127869
8,8,16,443,J/psi,44,6,443,J/psi,12.518738,2.248761,0.600298,3.096900
9,9,17,443,J/psi,44,7,443,J/psi,9.979537,-1.290865,-2.694251,3.127869
10,10,18,443,J/psi,44,8,443,J/psi,12.519975,2.244123,0.602188,3.096900
11,11,19,443,J/psi,44,9,443,J/psi,10.061036,-1.287518,-2.755375,3.127869
12,12,20,443,J/psi,44,10,443,J/psi,12.512180,2.242927,0.602640,3.096900
13,13,21,443,J/psi,44,11,443,J/psi,10.291659,-1.265527,-2.765127,3.127869
14,14,22,443,J/psi,44,12,443,J/psi,12.515298,2.240991,0.602576,3.096900
15,15,23,443,J/psi,44,13,443,J/psi,10.207764,-1.275886,-2.764932,3.127869
16,16,24,443,J/psi,44,14,443,J/psi,12.514161,2.239749,0.602265,3.096900
17,17,25,443,J/psi,44,15,443,J/psi,10.214492,-1.276401,-2.754599,3.127869
18,18,26,443,J/psi,2,16,443,J/psi,12.256836,2.259086,0.464549,3.096900
19,19,27,443,J/psi,2,17,443,J/psi,10.501187,-1.248621,-2.763592,3.127869
20,20,37,333,phi,2,-1,2212,2212,3.766093,2.213718,-2.163777,1.019542
21,21,39,333,phi,2,-1,2212,2212,0.351537,-1.880092,1.896473,1.020357
22,22,54,13,mu-,1,18,443,J/psi,2.818958,2.212904,0.930258,0.105658
23,23,55,-13,mu+,1,18,443,J/psi,9.820020,2.233661,0.335283,0.105658
24,24,56,13,mu-,1,19,443,J/psi,5.959050,-1.388788,-2.955797,0.105658
25,25,57,-13,mu+,1,19,443,J/psi,4.789120,-0.994810,-2.523607,0.105658
26,26,58,321,K+,1,20,333,phi,1.770991,2.282888,-2.168481,0.493680
27,27,59,-321,K-,1,20,333,phi,1.995138,2.148123,-2.159601,0.493680
28,28,60,321,K+,1,21,333,phi,0.147955,-2.232810,2.428941,0.493680
29,29,61,-321,K-,1,21,333,phi,0.236320,-1.386504,1.573028,0.493680

In [25]:
def candidate_muon_match_rows(tree, entry):
    snap = event_snapshot(tree, entry)
    tree.GetEntry(entry)
    candidate_specs = [
        ('Jpsi_1', getattr(tree, 'Jpsi_1_mu_1_Idx', []), getattr(tree, 'Jpsi_1_mu_2_Idx', [])),
        ('Jpsi_2', getattr(tree, 'Jpsi_2_mu_1_Idx', []), getattr(tree, 'Jpsi_2_mu_2_Idx', [])),
        ('Ups', getattr(tree, 'Ups_mu_1_Idx', []), getattr(tree, 'Ups_mu_2_Idx', [])),
    ]
    rows = []
    for label, idx1_vec, idx2_vec in candidate_specs:
        idx1_list = as_list(idx1_vec)
        idx2_list = as_list(idx2_vec)
        for cand_idx, (mu1_idx, mu2_idx) in enumerate(zip(idx1_list, idx2_list)):
            for role, mu_idx in (('daughter_1', int(mu1_idx)), ('daughter_2', int(mu2_idx))):
                if not (0 <= mu_idx < len(snap['mu_rows'])):
                    continue
                row = dict(snap['mu_rows'][mu_idx])
                row.update({
                    'candidate': label,
                    'candidate_index': cand_idx,
                    'role': role,
                })
                rows.append(row)
    return rows

def phi_candidate_kaon_rows(tree, entry):
    snap = event_snapshot(tree, entry)
    return snap['phi_rows']

display(maybe_frame(candidate_muon_match_rows(tree, ENTRY)))
display(maybe_frame(phi_candidate_kaon_rows(tree, ENTRY)))

,mu_idx,charge,pt,eta,phi,vertexId,match_idx,match_source,match_chi2,matched_pdg_id,matched_particle,matched_mother,matched_mother_idx,matched_gen_pt,candidate,candidate_index,role
0,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989,Jpsi_1,0,daughter_1
1,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168,Jpsi_1,0,daughter_2
2,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989,Jpsi_1,1,daughter_1
3,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168,Jpsi_1,1,daughter_2
4,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989,Jpsi_1,2,daughter_1
5,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168,Jpsi_1,2,daughter_2
6,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989,Jpsi_1,3,daughter_1
7,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168,Jpsi_1,3,daughter_2
8,0,1,10.634799,0.422053,0.581665,0,16,patRef,2.356401,-13,mu+,J/psi,12,10.547989,Jpsi_1,4,daughter_1
9,1,-1,3.924475,-0.049725,0.539034,0,15,patRef,1.155567,13,mu-,J/psi,12,3.939168,Jpsi_1,4,daughter_2
10,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267,Jpsi_2,0,daughter_1
11,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384,Jpsi_2,0,daughter_2
12,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267,Jpsi_2,1,daughter_1
13,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384,Jpsi_2,1,daughter_2
14,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267,Jpsi_2,2,daughter_1
15,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384,Jpsi_2,2,daughter_2
16,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267,Jpsi_2,3,daughter_1
17,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384,Jpsi_2,3,daughter_2
18,2,-1,3.588499,-1.349716,-2.003187,0,17,patRef,3.210236,13,mu-,J/psi,13,3.596267,Jpsi_2,4,daughter_1
19,3,1,3.258113,-2.048855,-2.598831,0,18,patRef,2.431783,-13,mu+,J/psi,13,3.163384,Jpsi_2,4,daughter_2

,phi_candidate,kaon_role,track_idx,phi_fit_pass,phi_commonAssocPVPass,phi_commonAssocPVIdx,phi_trackPVPass,phi_vertexCriteriaPass,phi_maxAbsDzPV,phi_maxAbsDxyPV,...,dxyPV,dzAssocPV,dxyAssocPV,gen_match_idx,gen_match_source,gen_match_chi2,matched_particle,matched_phi_gen_idx,matched_phi_particle,gen_chain
0,0,K1,832,1,1,0,1,1,0.038418,0.019014,...,-0.019014,0.038418,-0.019014,19,phiMotherChi2,10.372924,K+,14,phi,19:K+ <- 14:phi
1,1,K1,832,1,0,-1,1,0,1.682741,0.019014,...,-0.019014,0.038418,-0.019014,19,phiMotherChi2,10.372924,K+,14,phi,19:K+ <- 14:phi
2,2,K1,833,1,1,0,1,1,0.031543,0.005562,...,-0.003855,-0.031543,-0.003855,20,phiMotherChi2,4.812735,K-,14,phi,20:K- <- 14:phi
3,3,K1,866,1,1,1,0,0,8.418475,0.005603,...,-0.005603,0.024629,-0.007437,-1,unmatched,-1.000000,None,-1,None,None
4,4,K1,948,1,0,-1,0,0,13.468100,0.013655,...,0.002175,-0.017861,0.003550,-1,unmatched,-1.000000,None,-1,None,None
5,0,K2,833,1,1,0,1,1,0.038418,0.019014,...,-0.003855,-0.031543,-0.003855,20,phiMotherChi2,4.812735,K-,14,phi,20:K- <- 14:phi
6,1,K2,913,1,0,-1,1,0,1.682741,0.019014,...,-0.014120,-0.023750,-0.016475,-1,unmatched,-1.000000,None,-1,None,None
7,2,K2,834,1,1,0,1,1,0.031543,0.005562,...,-0.005562,0.008823,-0.005562,-1,unmatched,-1.000000,None,-1,None,None
8,3,K2,867,1,1,1,0,0,8.418475,0.005603,...,0.003739,0.012666,0.001815,-1,unmatched,-1.000000,None,-1,None,None
9,4,K2,991,1,0,-1,0,0,13.468100,0.013655,...,-0.013655,0.016484,-0.013115,-1,unmatched,-1.000000,None,-1,None,None

In [26]:
def scan_decay_signatures(tree, max_events=None):
    pair_counter = Counter()
    event_counter = Counter()
    n_entries = tree.GetEntries() if max_events is None else min(tree.GetEntries(), max_events)

    for entry in range(n_entries):
        snap = event_snapshot(tree, entry)
        pairs_in_event = set()
        for row in snap["gen_rows"]:
            key = (int(row["mother_pdg_id"]), int(row["pdg_id"]))
            pair_counter[key] += 1
            pairs_in_event.add(key)
        for key in pairs_in_event:
            event_counter[key] += 1

    rows = []
    for (mother, daughter), count in pair_counter.most_common():
        if abs(mother) not in {333, 443, 553} and abs(daughter) not in {13, 321, 333, 443, 553}:
            continue
        rows.append({
            "mother_pdg_id": mother,
            "mother": pdg_label(mother),
            "daughter_pdg_id": daughter,
            "daughter": pdg_label(daughter),
            "daughter_occurrences": count,
            "events_with_signature": event_counter[(mother, daughter)],
        })
    return rows

display(maybe_frame(scan_decay_signatures(tree, max_events=500)))

,mother_pdg_id,mother,daughter_pdg_id,daughter,daughter_occurrences,events_with_signature
0,443,J/psi,443,J/psi,1360,119
1,21,21,443,J/psi,238,119
2,443,J/psi,13,mu-,238,119
3,443,J/psi,-13,mu+,238,119
4,333,phi,321,K+,159,119
5,333,phi,-321,K-,159,119
6,2212,2212,333,phi,157,117
7,421,421,-321,K-,4,4
8,-421,-421,321,K+,3,3
9,-431,-431,-321,K-,2,2
10,-421,-421,13,mu-,2,2
11,1,1,333,phi,1,1
12,421,421,-13,mu+,1,1
13,431,431,321,K+,1,1
14,-431,-431,13,mu-,1,1
15,421,421,321,K+,1,1
16,411,411,-13,mu+,1,1
17,411,411,-321,K-,1,1
18,431,431,333,phi,1,1
19,-411,-411,321,K+,1,1
20,-411,-411,13,mu-,1,1

In [27]:
def match_source_breakdown(tree, max_events=None):
    source_counter = Counter()
    chi2_values = []
    phi_candidate_rows = []
    n_entries = tree.GetEntries() if max_events is None else min(tree.GetEntries(), max_events)

    for entry in range(n_entries):
        snap = event_snapshot(tree, entry)
        for row in snap["mu_rows"]:
            source_counter[row["match_source"]] += 1
            if row["match_source"] == "chi2Fallback" and row["match_chi2"] is not None:
                chi2_values.append(row["match_chi2"])

        seen_phi = set()
        for row in snap['phi_rows']:
            key = row['phi_candidate']
            if key in seen_phi:
                continue
            seen_phi.add(key)
            phi_candidate_rows.append({
                'entry': entry,
                'phi_candidate': key,
                'fit_pass': row['phi_fit_pass'],
                'commonAssocPVPass': row['phi_commonAssocPVPass'],
                'commonAssocPVIdx': row['phi_commonAssocPVIdx'],
                'trackPVPass': row['phi_trackPVPass'],
                'vertexCriteriaPass': row['phi_vertexCriteriaPass'],
                'maxAbsDzPV': row['phi_maxAbsDzPV'],
                'maxAbsDxyPV': row['phi_maxAbsDxyPV'],
            })

    rows = [{"source": key, "count": value} for key, value in sorted(source_counter.items())]
    display(maybe_frame(rows))
    if chi2_values:
        print({
            "fallback_matches": len(chi2_values),
            "chi2_min": min(chi2_values),
            "chi2_mean": sum(chi2_values) / len(chi2_values),
            "chi2_max": max(chi2_values),
        })
    display(maybe_frame(phi_candidate_rows))

match_source_breakdown(tree)

         source  count
0  chi2Fallback      3
1        patRef    451
2     unmatched    280

{'fallback_matches': 3, 'chi2_min': 1.795973300933838, 'chi2_mean': 2.314817190170288, 'chi2_max': 2.68038272857666}

,entry,phi_candidate,fit_pass,commonAssocPVPass,commonAssocPVIdx,trackPVPass,vertexCriteriaPass,maxAbsDzPV,maxAbsDxyPV
0,0,0,1,1,0,1,1,0.002147,0.004021
1,1,0,1,0,-1,0,0,13.945457,1.628586
2,1,1,1,0,-1,0,0,3.173652,0.664046
3,1,2,1,0,-1,0,0,1.113125,0.817904
4,1,3,1,0,-1,0,0,1.113125,0.817904
...,...,...,...,...,...,...,...,...,...
1177,118,14,1,1,0,1,1,0.004746,0.002563
1178,118,15,1,1,0,1,1,0.005234,0.002563
1179,118,16,1,0,-1,0,0,3.942512,0.041496
1180,118,17,1,0,-1,0,0,3.937043,1.802916
1181,118,18,1,0,-1,0,0,4.971430,1.802916

## MC Retention Switch Validation

This section compares the paired DPS validation ntuples produced with `ConfFile_cfg.py` on the same `10000`-event input slice:

- `RequireAcceptedCandidatesForMonteCarloTree=False`: keep every processed MC event and retain GEN info even when no stored candidate survives.
- `RequireAcceptedCandidatesForMonteCarloTree=True`: keep only events with at least one stored candidate, while preserving the same GEN and reco-matching content for those kept events.

In [28]:
def open_tree_for_path(path):
    if not path.exists():
        return None, None
    root_handle = ROOT.TFile.Open(str(path), 'READ')
    if not root_handle or root_handle.IsZombie():
        return None, None
    tree_handle = root_handle.Get(TREE_PATH)
    if not tree_handle:
        root_handle.Close()
        return None, None
    return root_handle, tree_handle

retention_handles = {}
retention_trees = {}
retention_rows = []
for label, path in RETENTION_VALIDATION_NTUPLES.items():
    handle, tree_handle = open_tree_for_path(path)
    if tree_handle is None:
        retention_rows.append({
            'sample': label,
            'path': str(path),
            'available': False,
        })
        continue
    retention_handles[label] = handle
    retention_trees[label] = tree_handle
    retention_rows.append({
        'sample': label,
        'path': str(path),
        'available': True,
        'entries': int(tree_handle.GetEntries()),
        'events_gen_nonempty': int(tree_handle.GetEntries('Length$(MC_GenPart_pdgId)>0')),
        'events_with_candidates': int(tree_handle.GetEntries('Length$(Pri_VtxProb)>0')),
        'events_without_candidates': int(tree_handle.GetEntries('Length$(Pri_VtxProb)==0')),
    })

display(maybe_frame(retention_rows))

,sample,path,available
0,keep_all_mc_events,/tmp/conf_dps120_switch_false_numEvent10000.root,False
1,require_candidates,/tmp/conf_dps120_switch_true_numEvent10000.root,False

In [29]:
def event_key_counter(tree, require_candidates=None):
    counter = Counter()
    for entry in range(tree.GetEntries()):
        snap = event_snapshot(tree, entry)
        has_candidate = bool(snap['phi_rows']) or len(as_list(getattr(tree, 'Pri_VtxProb', []))) > 0
        if require_candidates is True and not has_candidate:
            continue
        if require_candidates is False and has_candidate:
            continue
        counter[(snap["run"], snap["lumi"], snap["event"])] += 1
    return counter

def muon_match_counts(tree, require_candidates=None):
    counter = Counter()
    for entry in range(tree.GetEntries()):
        snap = event_snapshot(tree, entry)
        has_candidate = bool(snap['phi_rows']) or len(as_list(getattr(tree, 'Pri_VtxProb', []))) > 0
        if require_candidates is True and not has_candidate:
            continue
        if require_candidates is False and has_candidate:
            continue
        counter.update(row["match_source"] for row in snap["mu_rows"])
    return counter

false_tree = retention_trees.get('keep_all_mc_events')
true_tree = retention_trees.get('require_candidates')
if false_tree and true_tree:
    false_candidate_counter = event_key_counter(false_tree, require_candidates=True)
    true_counter = event_key_counter(true_tree)
    missing_from_true = false_candidate_counter - true_counter
    extra_in_true = true_counter - false_candidate_counter
    print({
        'false_candidate_entries': int(sum(false_candidate_counter.values())),
        'true_entries': int(sum(true_counter.values())),
        'distinct_false_candidate_keys': int(len(false_candidate_counter)),
        'distinct_true_keys': int(len(true_counter)),
        'missing_entry_multiplicity': int(sum(missing_from_true.values())),
        'extra_entry_multiplicity': int(sum(extra_in_true.values())),
    })

    false_mu_counter = muon_match_counts(false_tree, require_candidates=True)
    true_mu_counter = muon_match_counts(true_tree)
    display(maybe_frame([
        {
            'source': source,
            'false_candidate_subset': int(false_mu_counter.get(source, 0)),
            'true_tree': int(true_mu_counter.get(source, 0)),
        }
        for source in sorted(set(false_mu_counter) | set(true_mu_counter))
    ]))
else:
    print('Retention validation ntuples are not both available; skip this section or update RETENTION_VALIDATION_NTUPLES.')

Retention validation ntuples are not both available; skip this section or update RETENTION_VALIDATION_NTUPLES.

## Suggested Follow-ups

- Change `ENTRY` only if you want to inspect a different signal-like event; by default the notebook now picks the first entry with a stored `phi` candidate.
- Point `RETENTION_VALIDATION_NTUPLES` at a different false/true ntuple pair if you want to repeat the MC-retention validation on another sample or cut set.
- Filter `phi_rows` by `phi_vertexCriteriaPass == 1` or `passTrackPV == 0` to study which kaon-side PV requirement is failing.
- Compare `phi_commonAssocPVIdx`, `vertexId`, `dzPV`, and `dxyPV` against `Pri_*` acceptance diagnostics when studying why combined candidates fail or survive.
- Filter the GEN table by `matched_phi_gen_idx` to inspect only kaons that trace back to stored GEN `phi` ancestors.